//! Pinned `IANA` zone evidence for the Kernel `UserAutomation` occurrence contract.
//!
//! A normalized occurrence records the zone it was normalized against, the local
//! wall clock, the UTC offset the owner applied, the instant it resolves to, and
//! the fold or gap disposition. Deciding whether that record is *true* requires
//! knowing what offsets the named zone actually applied, at that instant, in
//! exactly one pinned release of the `IANA` database. A spelling heuristic cannot
//! answer that, and an ambient machine database would let two processes disagree
//! about the same revision.
//!
//! This module is the zone-evidence provider. It reads offsets and transitions
//! out of one committed, digest-pinned table generated by
//! `scripts/gen_user_automation_zone_table.py` from an extracted IANA release,
//! and answers three questions about a named zone:
//!
//! - the UTC offset in force at an instant;
//! - the two bracketing offsets and the transition instant between them;
//! - whether a local wall clock is unique, ambiguous (a fold) or nonexistent (a
//!   gap) in that zone.
//!
//! Every answer is confined to the table's closed coverage window. An instant or
//! a local clock outside it is refused with a typed error and is never
//! extrapolated, and a zone the table does not carry is refused rather than
//! resolved from its spelling. A zone whose expansion could not be proven
//! against an independent implementation of the same IANA data is withheld from
//! the table and named in its header, so it is refused here like any other
//! unknown zone.
//!
//! The table bytes are verified once against [`PINNED_ZONE_TABLE_SHA256`] with
//! [`eliot_contracts::sha256_hex`]; a mismatch makes every lookup in this module
//! fail closed rather than answer from bytes that are not the pinned release.

use std::collections::BTreeSet;
use std::sync::OnceLock;

use eliot_contracts::sha256_hex;

/// The committed zone table, embedded at compile time.
const PINNED_ZONE_TABLE: &str = include_str!("user_automation_zone_table.tzd");

/// SHA-256 of [`PINNED_ZONE_TABLE`]'s exact bytes.
///
/// Regenerating the table changes this constant, which is a deliberate, visible
/// act: a database update can never silently rewrite an existing revision.
const PINNED_ZONE_TABLE_SHA256: &str =
    "edd104d125063e5d6fb31e02adb0fd2dc8f0d268886f0274e7488a926b4a17a6";

/// The only zone database release this build admits.
pub(crate) const PINNED_ZONE_DATABASE_RELEASE: &str = "2026c";

/// Format tag the table header must carry.
pub(crate) const ZONE_TABLE_FORMAT: &str = "eliot.user-automation.zone-table.v1";

/// Inclusive first instant of the admitted window: `1970-01-01T00:00:00Z`.
pub(crate) const ZONE_TABLE_WINDOW_START_SECONDS: i64 = 0;

/// Exclusive last instant of the admitted window: `2100-01-01T00:00:00Z`.
pub(crate) const ZONE_TABLE_WINDOW_END_EXCLUSIVE_SECONDS: i64 = 4_102_444_800;

/// First instant the stored offset timeline covers, which is the admitted window
/// start less a two-day margin so that resolving a local wall clock near the
/// window edge never needs an offset the table does not carry.
pub(crate) const ZONE_TABLE_START_SECONDS: i64 = -172_800;

/// Exclusive last instant the stored offset timeline covers.
pub(crate) const ZONE_TABLE_END_EXCLUSIVE_SECONDS: i64 = 4_102_617_600;

/// Seconds in one civil minute, used to move between an offset and an instant.
const SECONDS_PER_MINUTE: i64 = 60;

/// Why the pinned zone table could not answer a question.
///
/// These are deliberately not contract errors: the caller maps them onto the
/// typed refusals of the `UserAutomation` contract, which is what decides what a
/// caller is told.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ZoneTableError {
    /// The embedded table bytes are not the pinned digest, or are not readable as
    /// the pinned format. Every lookup fails closed.
    Integrity,
    /// The zone is not a member of the pinned table. A withheld zone, a zone the
    /// pinned release does not define, and an invented spelling are all this.
    UnknownZone,
    /// The instant, or an instant the question needs, is outside the table's
    /// coverage. Nothing is extrapolated.
    OutsideCoverage,
}

/// The two offsets and the instant of one real transition in a named zone.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct ZoneTransition {
    /// UTC instant at which the post-transition offset takes effect.
    pub instant_seconds: i64,
    /// Offset in force immediately before `instant_seconds`.
    pub pre_offset_minutes: i32,
    /// Offset in force at and after `instant_seconds`.
    pub post_offset_minutes: i32,
}

/// What a local civil wall clock actually is in a named zone.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum LocalClockReality {
    /// The local wall clock occurs exactly once.
    Unique {
        /// The only instant that renders this local wall clock.
        instant_seconds: i64,
        /// The offset that instant carries.
        offset_minutes: i32,
    },
    /// The local wall clock occurs twice; the zone repeated it.
    Fold {
        /// The earlier of the two instants.
        first_instant_seconds: i64,
        /// Offset carried by `first_instant_seconds`.
        first_offset_minutes: i32,
        /// The later of the two instants.
        second_instant_seconds: i64,
        /// Offset carried by `second_instant_seconds`.
        second_offset_minutes: i32,
        /// The real transition that makes this local wall clock ambiguous.
        transition: ZoneTransition,
    },
    /// The local wall clock never occurs; the zone skipped it.
    Gap {
        /// The real transition that makes this local wall clock nonexistent.
        transition: ZoneTransition,
        /// The first local wall clock that does exist after the skip, which is
        /// the local clock the owner's shift-forward disposition lands on.
        shifted_local_unix_seconds: i64,
        /// The instant that shifted local wall clock resolves to, which is the
        /// table's real post-transition instant.
        resolved_instant_seconds: i64,
        /// Offset carried by `resolved_instant_seconds`.
        post_offset_minutes: i32,
    },
}

/// One zone's closed offset timeline: the offset at [`ZONE_TABLE_START_SECONDS`]
/// followed by one entry per instant where the offset changes.
struct ZoneTimeline {
    name: &'static str,
    events: Vec<(i64, i32)>,
}

/// The parsed, digest-verified pinned table.
struct ZoneTable {
    /// Zones sorted by name, so a lookup is a binary search over a closed set.
    zones: Vec<ZoneTimeline>,
}

/// The table is parsed and its bytes verified exactly once per process.
static PINNED_ZONE_TABLE_STATE: OnceLock<Result<ZoneTable, ZoneTableError>> = OnceLock::new();

impl ZoneTable {
    /// Parses the embedded bytes, refusing anything that is not the pinned
    /// format, the pinned release, or structurally inconsistent.
    fn parse(bytes: &'static str) -> Result<Self, ZoneTableError> {
        let mut format = None;
        let mut release = None;
        let mut zone_count: Option<usize> = None;
        let mut transition_count: Option<usize> = None;
        let mut window: Option<(i64, i64)> = None;
        let mut coverage: Option<(i64, i64)> = None;
        let mut zones: Vec<ZoneTimeline> = Vec::new();
        let mut transitions = 0usize;

        for line in bytes.lines() {
            if let Some(header) = line.strip_prefix('#') {
                let mut words = header.split_whitespace();
                match (words.next(), words.next()) {
                    (Some("format"), Some(value)) => format = Some(value.to_owned()),
                    (Some("release"), Some(value)) => release = Some(value.to_owned()),
                    (Some("zone_count"), Some(value)) => {
                        zone_count = Some(parse_count(value)?);
                    }
                    (Some("transition_count"), Some(value)) => {
                        transition_count = Some(parse_count(value)?);
                    }
                    (Some("window_start_seconds"), Some(value)) => {
                        let start = parse_i64(value)?;
                        window = Some((
                            start,
                            window.map_or(ZONE_TABLE_WINDOW_END_EXCLUSIVE_SECONDS, |w| w.1),
                        ));
                    }
                    (Some("window_end_exclusive_seconds"), Some(value)) => {
                        let end = parse_i64(value)?;
                        window =
                            Some((window.map_or(ZONE_TABLE_WINDOW_START_SECONDS, |w| w.0), end));
                    }
                    (Some("table_start_seconds"), Some(value)) => {
                        let start = parse_i64(value)?;
                        coverage = Some((
                            start,
                            coverage.map_or(ZONE_TABLE_END_EXCLUSIVE_SECONDS, |c| c.1),
                        ));
                    }
                    (Some("table_end_exclusive_seconds"), Some(value)) => {
                        let end = parse_i64(value)?;
                        coverage = Some((coverage.map_or(ZONE_TABLE_START_SECONDS, |c| c.0), end));
                    }
                    _ => {}
                }
                continue;
            }
            if line.is_empty() {
                continue;
            }
            if let Some(name) = line.strip_prefix("Z ") {
                if name.is_empty() || name.contains(' ') {
                    return Err(ZoneTableError::Integrity);
                }
                zones.push(ZoneTimeline {
                    name,
                    events: Vec::new(),
                });
                continue;
            }
            let current = zones.last_mut().ok_or(ZoneTableError::Integrity)?;
            let (instant, offset) = line.split_once(' ').ok_or(ZoneTableError::Integrity)?;
            let instant = parse_i64(instant)?;
            let offset = parse_i32(offset)?;
            if !(ZONE_TABLE_START_SECONDS..ZONE_TABLE_END_EXCLUSIVE_SECONDS).contains(&instant) {
                return Err(ZoneTableError::Integrity);
            }
            if current
                .events
                .last()
                .is_some_and(|(previous, _)| *previous >= instant)
            {
                return Err(ZoneTableError::Integrity);
            }
            current.events.push((instant, offset));
            transitions += 1;
        }

        if format.as_deref() != Some(ZONE_TABLE_FORMAT)
            || release.as_deref() != Some(PINNED_ZONE_DATABASE_RELEASE)
        {
            return Err(ZoneTableError::Integrity);
        }
        if window
            != Some((
                ZONE_TABLE_WINDOW_START_SECONDS,
                ZONE_TABLE_WINDOW_END_EXCLUSIVE_SECONDS,
            ))
            || coverage != Some((ZONE_TABLE_START_SECONDS, ZONE_TABLE_END_EXCLUSIVE_SECONDS))
        {
            return Err(ZoneTableError::Integrity);
        }
        if zone_count != Some(zones.len()) || transition_count != Some(transitions) {
            return Err(ZoneTableError::Integrity);
        }
        if !Self::is_structurally_sound(&zones) {
            return Err(ZoneTableError::Integrity);
        }
        Ok(Self { zones })
    }

    /// Returns whether every zone is non-empty, rooted at the coverage start, and
    /// the zone names are strictly ascending, so a lookup is a binary search.
    fn is_structurally_sound(zones: &[ZoneTimeline]) -> bool {
        zones
            .iter()
            .all(|zone| !zone.events.is_empty() && zone.events[0].0 == ZONE_TABLE_START_SECONDS)
            && !zones.windows(2).any(|pair| pair[0].name >= pair[1].name)
    }

    /// Returns the closed timeline of one named zone.
    fn timeline(&self, zone: &str) -> Result<&[(i64, i32)], ZoneTableError> {
        self.zones
            .binary_search_by(|candidate| candidate.name.cmp(zone))
            .map(|index| self.zones[index].events.as_slice())
            .map_err(|_| ZoneTableError::UnknownZone)
    }

    /// Returns the offset in force at `instant_seconds`.
    fn offset_at(&self, zone: &str, instant_seconds: i64) -> Result<i32, ZoneTableError> {
        if !(ZONE_TABLE_START_SECONDS..ZONE_TABLE_END_EXCLUSIVE_SECONDS).contains(&instant_seconds)
        {
            return Err(ZoneTableError::OutsideCoverage);
        }
        let events = self.timeline(zone)?;
        let mut low = 0usize;
        let mut high = events.len();
        while low < high {
            let middle = low + (high - low) / 2;
            if events[middle].0 <= instant_seconds {
                low = middle + 1;
            } else {
                high = middle;
            }
        }
        Ok(events[low - 1].1)
    }
}

/// Returns the transition that brackets `local_unix_seconds`, if any.
///
/// A real transition at `instant` brackets a local wall clock exactly when the
/// clock is unreachable from either side of it, which is the shared shape of a
/// fold and a gap: the clock resolves through the offset before the transition,
/// through the offset after it, or through neither.
fn bracketing_transition(events: &[(i64, i32)], local_unix_seconds: i64) -> Option<ZoneTransition> {
    for (index, (instant, post)) in events.iter().enumerate().skip(1) {
        let pre = events[index - 1].1;
        if pre == *post {
            continue;
        }
        let lower = local_unix_seconds - i64::from(*post) * SECONDS_PER_MINUTE;
        let upper = local_unix_seconds - i64::from(pre) * SECONDS_PER_MINUTE;
        let (first, last) = if lower <= upper {
            (lower, upper)
        } else {
            (upper, lower)
        };
        if first < *instant && *instant <= last {
            return Some(ZoneTransition {
                instant_seconds: *instant,
                pre_offset_minutes: pre,
                post_offset_minutes: *post,
            });
        }
    }
    None
}

/// Parses a non-negative decimal count from the table header.
fn parse_count(value: &str) -> Result<usize, ZoneTableError> {
    value
        .parse::<usize>()
        .map_err(|_| ZoneTableError::Integrity)
}

/// Parses a signed decimal second count from the table header or body.
fn parse_i64(value: &str) -> Result<i64, ZoneTableError> {
    value.parse::<i64>().map_err(|_| ZoneTableError::Integrity)
}

/// Parses a signed decimal minute offset from the table body.
fn parse_i32(value: &str) -> Result<i32, ZoneTableError> {
    value.parse::<i32>().map_err(|_| ZoneTableError::Integrity)
}

/// Returns the verified table, verifying the embedded bytes on first use.
///
/// The digest is taken over the table with `CRLF` line endings folded to `LF`.
/// The repository has no line-ending rule for this file, so a checkout on a host
/// that rewrites line endings would otherwise embed different bytes for
/// byte-identical data and fail every lookup closed. Folding only `CRLF` leaves
/// the pinned content exact: any other byte difference, and any data difference,
/// still fails the check. [`ZoneTable::parse`] additionally re-validates the
/// format, the release, the window and the declared counts, so the digest is a
/// pin on the data rather than the only thing standing between the table and a
/// caller.
fn pinned_table() -> Result<&'static ZoneTable, ZoneTableError> {
    PINNED_ZONE_TABLE_STATE
        .get_or_init(|| {
            let normalized = PINNED_ZONE_TABLE.replace("\r\n", "\n");
            if sha256_hex(normalized.as_bytes()) != PINNED_ZONE_TABLE_SHA256 {
                return Err(ZoneTableError::Integrity);
            }
            ZoneTable::parse(PINNED_ZONE_TABLE)
        })
        .as_ref()
        .map_err(|error| *error)
}

/// Returns whether `zone` is a member of the pinned, proven table.
///
/// This is the whole of zone admission. A name the pinned release does not
/// define, a withheld zone, and a spelled pair that resembles a real one are all
/// absent here, so all of them are refused identically.
pub(crate) fn is_pinned_zone(zone: &str) -> bool {
    pinned_table().is_ok_and(|table| table.timeline(zone).is_ok())
}

/// Returns the offset in force in `zone` at `instant_seconds`.
pub(crate) fn offset_minutes_at(zone: &str, instant_seconds: i64) -> Result<i32, ZoneTableError> {
    pinned_table()?.offset_at(zone, instant_seconds)
}

/// Returns what the local wall clock `local_unix_seconds` really is in `zone`.
///
/// `local_unix_seconds` is the local wall clock read as if it were UTC, which is
/// the same reading the occurrence record's local field already gives. The
/// distinct offsets the zone actually uses are tried against it, so the answer
/// is exact rather than a search for one transition.
pub(crate) fn classify_local_clock(
    zone: &str,
    local_unix_seconds: i64,
) -> Result<LocalClockReality, ZoneTableError> {
    let table = pinned_table()?;
    let events = table.timeline(zone)?;
    let distinct: BTreeSet<i32> = events.iter().map(|(_, offset)| *offset).collect();

    let mut candidates: Vec<(i64, i32)> = Vec::new();
    for offset in distinct {
        let instant = local_unix_seconds - i64::from(offset) * SECONDS_PER_MINUTE;
        if table.offset_at(zone, instant)? == offset {
            candidates.push((instant, offset));
        }
    }
    candidates.sort_unstable();

    match candidates.as_slice() {
        [] => {
            let transition = bracketing_transition(events, local_unix_seconds)
                .ok_or(ZoneTableError::OutsideCoverage)?;
            let resolved =
                local_unix_seconds - i64::from(transition.pre_offset_minutes) * SECONDS_PER_MINUTE;
            if table.offset_at(zone, resolved)? != transition.post_offset_minutes {
                return Err(ZoneTableError::Integrity);
            }
            Ok(LocalClockReality::Gap {
                transition,
                shifted_local_unix_seconds: resolved
                    + i64::from(transition.post_offset_minutes) * SECONDS_PER_MINUTE,
                resolved_instant_seconds: resolved,
                post_offset_minutes: transition.post_offset_minutes,
            })
        }
        [(instant, offset)] => Ok(LocalClockReality::Unique {
            instant_seconds: *instant,
            offset_minutes: *offset,
        }),
        [
            (first_instant, first_offset),
            (second_instant, second_offset),
        ] => {
            let transition = bracketing_transition(events, local_unix_seconds)
                .ok_or(ZoneTableError::OutsideCoverage)?;
            Ok(LocalClockReality::Fold {
                first_instant_seconds: *first_instant,
                first_offset_minutes: *first_offset,
                second_instant_seconds: *second_instant,
                second_offset_minutes: *second_offset,
                transition,
            })
        }
        _ => Err(ZoneTableError::Integrity),
    }
}
