#!/usr/bin/env python3
"""Render the I7.20 reason-code projection from the protocol's Rust registry."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "crates/foundation/eliot-protocol/src/reason_codes.rs"
DESTINATION = ROOT / "docs/generated/reason-codes.md"
NORMATIVE_SOURCE = ROOT / "docs/architecture/I07-20-agent-facing-error-contract.md"

ENTRY = re.compile(
    r'AgentReasonCode\s*\{\s*group\s*:\s*"([^"\n]+)"\s*,\s*'
    r'code\s*:\s*"([A-Z][A-Z0-9_]*)"\s*,?\s*\}\s*,?'
)
ALIAS = re.compile(
    r'\(\s*"([A-Z][A-Z0-9_]*)"\s*,\s*'
    r'"([A-Z][A-Z0-9_]*)"\s*,?\s*\)\s*,?'
)
NORMATIVE_GROUP = re.compile(r'^([a-z]+(?:/[a-z]+)?)\s*—\s*(.*)$')
CANONICAL_CODE = re.compile(r'\b[A-Z][A-Z0-9_]*\b')


def array_entries(source: str, declaration: str, entry_pattern: re.Pattern[str]) -> list[tuple[str, ...]]:
    marker = f"{declaration} = &["
    _, found, after = source.partition(marker)
    if not found or marker in after:
        raise ValueError(f"protocol registry must contain exactly one {declaration} array")
    block, terminator, _ = after.partition("];")
    if not terminator:
        raise ValueError(f"protocol registry {declaration} array is not terminated")

    entries: list[tuple[str, ...]] = []
    remainder = block
    while remainder.strip():
        remainder = remainder.lstrip()
        match = entry_pattern.match(remainder)
        if match is None:
            raise ValueError(f"unrecognized entry in protocol registry {declaration} array")
        entries.append(match.groups())
        remainder = remainder[match.end():]
    if not entries:
        raise ValueError(f"protocol registry {declaration} array is empty")
    return entries


def normative_entries(source: str) -> list[tuple[str, str]]:
    marker = "Agent surfaces group reasons without changing their exact identity:"
    _, found, after = source.partition(marker)
    if not found:
        raise ValueError("I7.20 is missing its canonical agent-surface reason-code block")
    opening = after.find("```text")
    closing = after.find("```", opening + len("```text"))
    if opening < 0 or closing < 0:
        raise ValueError("I7.20 canonical reason-code block is malformed")
    block = after[opening + len("```text"):closing]

    expected: list[tuple[str, str]] = []
    group: str | None = None
    for raw_line in block.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        match = NORMATIVE_GROUP.match(line)
        if match:
            group, codes_text = match.groups()
        elif group is not None:
            codes_text = line
        else:
            raise ValueError("I7.20 canonical reason-code block has an unrecognized line")
        codes = CANONICAL_CODE.findall(codes_text)
        if not codes:
            raise ValueError("I7.20 canonical reason-code group is empty")
        expected.extend((group, code) for code in codes)
        if line.endswith(";") or line.endswith("."):
            group = None
    if group is not None or not expected:
        raise ValueError("I7.20 canonical reason-code block is incomplete")
    return expected


def render(source: str) -> str:
    entries = array_entries(source, "pub const AGENT_REASON_CODES: &[AgentReasonCode]", ENTRY)
    aliases = array_entries(source, "pub const BRIDGE_REASON_CODE_ALIASES: &[(&str, &str)]", ALIAS)
    normative = normative_entries(NORMATIVE_SOURCE.read_text(encoding="utf-8"))
    if entries != normative:
        raise ValueError("protocol reason registry does not exactly match the current I7.20 canonical set")

    codes = [code for _, code in entries]
    if len(codes) != len(set(codes)):
        raise ValueError("protocol registry contains duplicate canonical reason codes")
    if any(canonical not in set(codes) for _, canonical in aliases):
        raise ValueError("bridge alias target is absent from the canonical reason registry")
    if len({legacy for legacy, _ in aliases}) != len(aliases):
        raise ValueError("bridge alias table contains duplicate legacy names")

    groups: dict[str, list[str]] = {}
    for group, code in entries:
        groups.setdefault(group, []).append(code)

    lines = [
        "# Agent-facing reason-code registry",
        "",
        "Generated by `python scripts/generate_reason_codes.py` from the",
        "`eliot-protocol` Rust registry. Unknown additive reason-code strings remain",
        "valid and are relayed verbatim under their stable disposition.",
        "",
        "`CURRENT_DOCUMENTATION_PROJECTION`  ",
        "`DOCUMENTATION_ONLY`  ",
        "`ImplementationSupport = TARGET`  ",
        "`EvidenceExecutionStatus = NOT_EXECUTED`",
        "",
        "## Canonical reason codes",
        "",
    ]
    for group, group_codes in groups.items():
        lines.extend([f"### {group}", "", ", ".join(f"`{code}`" for code in group_codes), ""])

    lines.extend(
        [
            "## Bridge-only migration aliases",
            "",
            "This transport column is interpreted only at the bridge compatibility boundary.",
            "An identity mapping retains the same canonical spelling and does not create a second registry entry.",
            "",
            "| Legacy transport name | Canonical reason code |",
            "| --- | --- |",
        ]
    )
    lines.extend(f"| `{legacy}` | `{canonical}` |" for legacy, canonical in aliases)
    lines.extend([""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in projection differs from the Rust registry",
    )
    args = parser.parse_args()
    try:
        expected = render(SOURCE.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        parser.error(str(error))
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_text(encoding="utf-8") != expected:
            parser.error(f"{DESTINATION.relative_to(ROOT)} is stale; regenerate it")
        return 0
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
