[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$SchemaVersion = 'eliot-stu-observation-v1'
$Formula = 'ceil(UTF-8 bytes / 3), summed per included file'
$RootDirectiveSha256 = 'C12C3B15229286B887483BAE4B2B1CD8023F243897E84F77855D891EBE1E7BB4'
$TestSupportPackageName = 'eliot-test-support'
$NoSplitStatement = 'NO_SPLIT_AUTHORITY: this measurement assigns no Module split, recommends no Module split and forces no Module split; numeric band crossings are recorded as review evidence only because I2.16 states sizes never force a Module split by themselves.'
$DriftNote = 'Drift evidence only: the swarm/inventory/modules.json physical_source_STU aggregate remains opaque and is never subtracted from, corrected or revised by this measurement.'

$ClassProfiles = @(
    [pscustomobject]@{ crate_class = 'primitives/contracts'; starting_target = '5–15k STU'; review_band = '25k'; legacy_high_review_band = '40k'; review_band_upper_stu = 25000 },
    [pscustomobject]@{ crate_class = 'low-level hot-path primitive'; starting_target = '15–30k'; review_band = '40k'; legacy_high_review_band = '60k'; review_band_upper_stu = 40000 },
    [pscustomobject]@{ crate_class = 'pure component/domain core'; starting_target = '20–40k'; review_band = '55–60k'; legacy_high_review_band = '80k'; review_band_upper_stu = 60000 },
    [pscustomobject]@{ crate_class = 'control/service implementation'; starting_target = '30–50k'; review_band = '70k'; legacy_high_review_band = '100k'; review_band_upper_stu = 100000 },
    [pscustomobject]@{ crate_class = 'adapter/parser/bridge library'; starting_target = '5–20k'; review_band = '30k'; legacy_high_review_band = '45k'; review_band_upper_stu = 30000 },
    [pscustomobject]@{ crate_class = 'facade/composition/binary'; starting_target = '5–15k'; review_band = '25k'; legacy_high_review_band = '40k'; review_band_upper_stu = 25000 },
    [pscustomobject]@{ crate_class = 'shared test-support'; starting_target = '10–30k'; review_band = '45k'; legacy_high_review_band = '70k'; review_band_upper_stu = 45000 }
)

$ExclusionProfiles = [ordered]@{
    generated_code        = [pscustomobject]@{ exact_components = @('generated', 'gen', 'codegen', 'autogenerated'); filename_tokens = @('generated', 'autogenerated', 'codegen') }
    large_golden_corpora  = [pscustomobject]@{ exact_components = @('golden', 'goldens', 'corpus', 'corpora'); filename_tokens = @('golden', 'goldens') }
    vendor_source         = [pscustomobject]@{ exact_components = @('vendor', 'vendored', 'third-party', 'third_party'); filename_tokens = @('vendor', 'vendored') }
    raw_fixtures          = [pscustomobject]@{ exact_components = @('fixtures', 'fixture', 'testdata', 'test-data', 'fixture-template'); filename_tokens = @('fixture', 'fixtures') }
}

function Fail([string] $Message) {
    throw "STU_MEASURE_FAIL: $Message"
}

function Get-ClassProfile([string] $CrateClass) {
    foreach ($profile in $ClassProfiles) {
        if ($profile.crate_class -eq $CrateClass) {
            return $profile
        }
    }
    return $null
}

function Get-ExclusionCategory([string] $NormalizedPath) {
    $components = $NormalizedPath -split '/'
    foreach ($category in $ExclusionProfiles.Keys) {
        foreach ($component in $components) {
            foreach ($candidate in $ExclusionProfiles[$category].exact_components) {
                if ($component.Equals($candidate, [StringComparison]::OrdinalIgnoreCase)) {
                    return $category
                }
            }
        }
    }
    $filename = $components[-1]
    if ($filename.ToLowerInvariant().EndsWith('.rs')) {
        $stem = $filename.Substring(0, $filename.Length - 3)
        foreach ($category in $ExclusionProfiles.Keys) {
            foreach ($candidate in $ExclusionProfiles[$category].exact_components) {
                if ($stem.Equals($candidate, [StringComparison]::OrdinalIgnoreCase)) {
                    return $category
                }
            }
            foreach ($token in ($stem -split '[_-]')) {
                if ($token -eq '') {
                    continue
                }
                foreach ($candidate in $ExclusionProfiles[$category].filename_tokens) {
                    if ($token.Equals($candidate, [StringComparison]::OrdinalIgnoreCase)) {
                        return $category
                    }
                }
            }
        }
    }
    return $null
}

try {
    [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)

    $selfCheckPositives = @(
        [pscustomobject]@{ path = 'bins/eliot-watchdog/src/registry_fixture.rs'; category = 'raw_fixtures' },
        [pscustomobject]@{ path = 'crates/eliot-app/src/commands/skill_fixtures.rs'; category = 'raw_fixtures' },
        [pscustomobject]@{ path = 'tests/cognitive/ul-cross-agent/fixture-template/src/relay_alpha.rs'; category = 'raw_fixtures' },
        [pscustomobject]@{ path = 'crates/example/src/generated/schema.rs'; category = 'generated_code' },
        [pscustomobject]@{ path = 'tests/data/golden/summary.rs'; category = 'large_golden_corpora' },
        [pscustomobject]@{ path = 'vendor/lib/vendor.rs'; category = 'vendor_source' }
    )
    $selfCheckNegatives = @(
        'bins/eliot-watchdog/src/prefixture_like.rs',
        'crates/eliot-app/src/regolden_helper.rs',
        'crates/eliot-app/src/generators_util.rs',
        'crates/eliot-app/src/vendoring_tool.rs',
        'crates/eliot-app/src/corpus_reader.rs',
        'crates/eliot-app/src/testdata2_index.rs'
    )
    foreach ($case in $selfCheckPositives) {
        $selfCheckGot = Get-ExclusionCategory $case.path
        if ($selfCheckGot -ne $case.category) {
            Fail "exclusion self-check positive failed for '$($case.path)': expected '$($case.category)', got '$selfCheckGot'"
        }
    }
    foreach ($negativePath in $selfCheckNegatives) {
        $selfCheckGot = Get-ExclusionCategory $negativePath
        if ($null -ne $selfCheckGot) {
            Fail "exclusion self-check negative failed: '$negativePath' matched '$selfCheckGot' but must remain included"
        }
    }

    $repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

    $gitOutput = @(& git -C $repoRoot ls-files --cached -- '*.rs' 2>&1)
    $gitExit = $LASTEXITCODE
    if ($gitExit -ne 0) {
        Fail "git ls-files exited ${gitExit}: $($gitOutput -join ' ')"
    }
    $relativePaths = @(
        $gitOutput |
            ForEach-Object { $_.ToString().Trim() } |
            Where-Object { $_ -ne '' }
    )
    if ($relativePaths.Count -eq 0) {
        Fail 'tracked Rust source set is empty'
    }

    $headOutput = @(& git -C $repoRoot rev-parse HEAD 2>&1)
    if ($LASTEXITCODE -ne 0) {
        Fail "git rev-parse exited $($LASTEXITCODE): $($headOutput -join ' ')"
    }
    $headCommit = [string]$headOutput[0]
    if ($headCommit -notmatch '^[0-9a-f]{40}$') {
        Fail "unexpected git HEAD format: $headCommit"
    }

    $psi = [System.Diagnostics.ProcessStartInfo]::new()
    $psi.FileName = 'cargo'
    $psi.Arguments = 'metadata --locked --no-deps --format-version 1'
    $psi.WorkingDirectory = $repoRoot
    $psi.UseShellExecute = $false
    $psi.CreateNoWindow = $true
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    $proc = [System.Diagnostics.Process]::new()
    $proc.StartInfo = $psi
    if (-not $proc.Start()) {
        Fail 'could not start cargo metadata'
    }
    $metaStdout = $proc.StandardOutput.ReadToEnd()
    $metaStderr = $proc.StandardError.ReadToEnd()
    $proc.WaitForExit()
    if ($proc.ExitCode -ne 0) {
        Fail "cargo metadata exited $($proc.ExitCode): $metaStderr"
    }
    try {
        $meta = $metaStdout | ConvertFrom-Json
    }
    catch {
        Fail "cargo metadata emitted invalid JSON: $($_.Exception.Message)"
    }
    $packages = @($meta.packages)
    if ($packages.Count -eq 0) {
        Fail 'cargo metadata returned no packages'
    }
    $packageIds = @($packages | ForEach-Object { $_.id })
    $uniquePackageIds = @($packageIds | Sort-Object -Unique -Culture '')
    if ($uniquePackageIds.Count -ne $packageIds.Count) {
        Fail "cargo metadata returned duplicate package rows: $($packageIds.Count) rows, $($uniquePackageIds.Count) unique ids"
    }
    $metaRoot = ([string]$meta.workspace_root).TrimEnd('\', '/')
    if (-not $repoRoot.TrimEnd('\', '/').Equals($metaRoot, [StringComparison]::OrdinalIgnoreCase)) {
        Fail "cargo metadata workspace root '$metaRoot' does not match repository root '$repoRoot'"
    }

    $packageRows = @(foreach ($pkg in $packages) {
        if (-not $pkg.manifest_path) {
            Fail "package '$($pkg.name)' has no manifest_path"
        }
        $targets = @($pkg.targets)
        if ($targets.Count -eq 0) {
            Fail "package '$($pkg.name)' declares no targets"
        }
        $hasBin = $false
        foreach ($target in $targets) {
            if (@($target.kind) -contains 'bin') {
                $hasBin = $true
                break
            }
        }
        $rootDir = [System.IO.Path]::GetDirectoryName($pkg.manifest_path)
        $relRoot = [IO.Path]::GetRelativePath($repoRoot, $rootDir).Replace('\', '/')
        if ($relRoot -eq '' -or $relRoot -eq '.') {
            Fail "package '$($pkg.name)' resolves to the repository root, longest-root ownership would be ambiguous"
        }
        [pscustomobject]@{
            package_name = [string]$pkg.name
            manifest_rel = [IO.Path]::GetRelativePath($repoRoot, $pkg.manifest_path).Replace('\', '/')
            root         = $relRoot.TrimEnd('/')
            has_bin      = $hasBin
        }
    })
    $duplicateRoots = @($packageRows | Group-Object { $_.root.ToLowerInvariant() } | Where-Object Count -gt 1)
    if ($duplicateRoots.Count -gt 0) {
        Fail "multiple packages share one package root: $(($duplicateRoots | ForEach-Object Name) -join ', ')"
    }

    $statsByName = @{}
    foreach ($row in $packageRows) {
        if ($statsByName.ContainsKey($row.package_name)) {
            Fail "duplicate package name: $($row.package_name)"
        }
        $statsByName[$row.package_name] = [ordered]@{
            root     = $row.root
            manifest = $row.manifest_rel
            has_bin  = $row.has_bin
            stu      = [long]0
            bytes    = [long]0
            included = 0
            excluded = 0
            evidence = [System.Collections.Generic.List[object]]::new()
        }
    }

    $utf8Strict = [System.Text.UTF8Encoding]::new($false, $true)
    $unassigned = [System.Collections.Generic.List[object]]::new()
    $unownedExcluded = [System.Collections.Generic.List[object]]::new()
    $excludedTotal = 0
    $seenPaths = @{}
    $assignedCount = 0

    [Array]::Sort($relativePaths, [StringComparer]::Ordinal)
    foreach ($relativePath in $relativePaths) {
        if ($relativePath.Contains("`r") -or $relativePath.Contains("`n")) {
            Fail "tracked path contains a line break: $relativePath"
        }
        $normalizedPath = $relativePath.Replace('\', '/')
        if ($seenPaths.ContainsKey($normalizedPath)) {
            Fail "duplicate tracked path: $normalizedPath"
        }
        $seenPaths[$normalizedPath] = $true

        $nativeRelativePath = $normalizedPath.Replace('/', [IO.Path]::DirectorySeparatorChar)
        $fullPath = [IO.Path]::GetFullPath((Join-Path $repoRoot $nativeRelativePath))
        $rootPrefix = $repoRoot.TrimEnd('\', '/') + [IO.Path]::DirectorySeparatorChar
        if (-not $fullPath.StartsWith($rootPrefix, [StringComparison]::OrdinalIgnoreCase)) {
            Fail "tracked path escapes repository root: $normalizedPath"
        }
        if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
            Fail "tracked Rust file is missing: $normalizedPath"
        }

        $exclusionCategory = Get-ExclusionCategory $normalizedPath
        $owner = $null
        foreach ($row in $packageRows) {
            $prefix = $row.root + '/'
            if ($normalizedPath.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
                if ($null -eq $owner -or $row.root.Length -gt $owner.root.Length) {
                    $owner = $row
                }
            }
        }
        if ($null -ne $exclusionCategory) {
            $excludedTotal++
            if ($null -eq $owner) {
                [void]$unownedExcluded.Add([pscustomobject]@{
                    path    = $normalizedPath
                    profile = $exclusionCategory
                    reason  = 'EXCLUDED_OUTSIDE_PACKAGE_ROOT'
                })
                continue
            }
            $assignedCount++
            $record = $statsByName[$owner.package_name]
            $record.excluded++
            [void]$record.evidence.Add([pscustomobject]@{
                path    = $normalizedPath
                profile = $exclusionCategory
            })
            continue
        }
        if ($null -eq $owner) {
            [void]$unassigned.Add([pscustomobject]@{
                path   = $normalizedPath
                reason = 'NO_PACKAGE_ROOT'
            })
            continue
        }
        $assignedCount++

        $bytes = [IO.File]::ReadAllBytes($fullPath)
        try {
            $utf8Strict.GetString($bytes) | Out-Null
        }
        catch {
            Fail "tracked Rust file is not valid UTF-8: $normalizedPath"
        }
        $record = $statsByName[$owner.package_name]

        $record.bytes += [long]$bytes.Length
        $record.stu += [long][math]::Ceiling($bytes.Length / 3.0)
        $record.included++
    }

    $inventoryPath = Join-Path $repoRoot 'swarm/inventory/modules.json'
    $inventoryStu = @{}
    $inventoryStatus = 'AVAILABLE'
    $inventoryReason = $null
    if (-not (Test-Path -LiteralPath $inventoryPath -PathType Leaf)) {
        $inventoryStatus = 'UNAVAILABLE'
        $inventoryReason = 'INVENTORY_FILE_MISSING'
    }
    else {
        try {
            $inventory = Get-Content -LiteralPath $inventoryPath -Raw | ConvertFrom-Json
            foreach ($entry in @($inventory.manifests)) {
                if ($inventoryStu.ContainsKey($entry.package_name)) {
                    throw "duplicate inventory package row: $($entry.package_name)"
                }
                $inventoryStu[$entry.package_name] = [long]$entry.physical_source_STU.total_stu
            }
        }
        catch {
            $inventoryStatus = 'UNAVAILABLE'
            $inventoryReason = "INVENTORY_PARSE_FAILED: $($_.Exception.Message)"
            $inventoryStu.Clear()
        }
    }

    $packageNames = @($statsByName.Keys)
    [Array]::Sort($packageNames, [StringComparer]::Ordinal)
    $records = [System.Collections.Generic.List[object]]::new()
    $classifiedCount = 0
    $unknownCount = 0
    foreach ($packageName in $packageNames) {
        $record = $statsByName[$packageName]
        $crateClass = 'UNKNOWN'
        $classificationStatus = 'UNKNOWN'
        $classificationBasis = $null
        $startingTarget = $null
        $reviewBand = $null
        $legacyHighReviewBand = $null
        $bandCrossing = $null
        $profile = $null

        if ($packageName -eq $TestSupportPackageName) {
            $crateClass = 'shared test-support'
            $classificationStatus = 'CLASSIFIED'
            $classificationBasis = 'EXACT_PACKAGE_NAME_ELIGIBLE_TEST_SUPPORT'
        }
        elseif ($record.has_bin) {
            $crateClass = 'facade/composition/binary'
            $classificationStatus = 'CLASSIFIED'
            $classificationBasis = 'BIN_TARGET_PRESENT'
        }

        if ($classificationStatus -eq 'CLASSIFIED') {
            $classifiedCount++
            $profile = Get-ClassProfile $crateClass
            if ($null -eq $profile) {
                Fail "assigned class '$crateClass' is not one of the seven I2.16 class profiles"
            }
            $startingTarget = $profile.starting_target
            $reviewBand = $profile.review_band
            $legacyHighReviewBand = $profile.legacy_high_review_band
            if ($record.stu -ge $profile.review_band_upper_stu) {
                $bandCrossing = 'AT_OR_ABOVE_REVIEW_BAND_OBSERVATION_ONLY'
            }
            else {
                $bandCrossing = 'BELOW_REVIEW_BAND'
            }
        }
        else {
            $unknownCount++
        }

        if ($record.evidence.Count -gt 0) {
            $exclusionStatus = 'EXCLUSIONS_APPLIED'
        }
        else {
            $exclusionStatus = 'NONE_APPLIED'
        }

        $inventoryTotal = $null
        $deltaStu = $null
        $comparisonStatus = $null
        switch ($inventoryStatus) {
            'AVAILABLE' {
                if (-not $inventoryStu.ContainsKey($packageName)) {
                    $comparisonStatus = 'INVENTORY_ENTRY_MISSING'
                }
                else {
                    $inventoryTotal = $inventoryStu[$packageName]
                    $deltaStu = $record.stu - $inventoryTotal
                    if ($deltaStu -eq 0) {
                        $comparisonStatus = 'INVENTORY_MATCH'
                    }
                    else {
                        $comparisonStatus = 'INVENTORY_DRIFT_OBSERVATION_ONLY'
                    }
                }
            }
            default {
                $comparisonStatus = 'INVENTORY_UNAVAILABLE'
            }
        }

        [void]$records.Add([pscustomobject]@{
            package_name             = $packageName
            manifest_path            = $record.manifest
            package_root             = $record.root
            has_bin_target           = [bool]$record.has_bin
            classification_status    = $classificationStatus
            crate_class              = $crateClass
            starting_target          = $startingTarget
            review_band              = $reviewBand
            legacy_high_review_band  = $legacyHighReviewBand
            classification_basis     = $classificationBasis
            included_file_count      = $record.included
            excluded_file_count      = $record.excluded
            utf8_bytes_total         = $record.bytes
            stu                      = $record.stu
            band_crossing            = $bandCrossing
            exclusion_status         = $exclusionStatus
            exclusion_evidence       = @($record.evidence.ToArray())
            inventory_comparison     = [pscustomobject]@{
                status                                = $comparisonStatus
                inventory_physical_source_STU_total_stu = $inventoryTotal
                local_stu                             = $record.stu
                delta_stu                             = $deltaStu
                note                                  = $DriftNote
            }
            blocking                 = $false
        })
    }

    $totalIncluded = 0
    $totalStu = [long]0
    foreach ($packageName in $packageNames) {
        $record = $statsByName[$packageName]
        $totalIncluded += $record.included
        $totalStu += $record.stu
    }

    $document = [pscustomobject][ordered]@{
        schema_version = $SchemaVersion
        status         = 'REVIEW_NON_BLOCKING_OBSERVATION'
        formula        = $Formula
        scope          = 'workspace crates: tracked Rust files (*.rs) assigned to their unique longest package root'
        authority      = [pscustomobject]@{
            root_directive           = 'swarm/decisions/ROOT-DIRECTIVE-v1.5.md section 3.3 (Ox-4 lane)'
            root_directive_sha256    = $RootDirectiveSha256
            class_profiles_anchor    = 'ELIOT_IMPLEMENTATION.md:3007-3015 (I2.16)'
            exclusion_anchor         = 'ELIOT_IMPLEMENTATION.md:3005'
            head_commit_at_emission  = $headCommit
        }
        source_universe = [pscustomobject]@{
            cargo_metadata_command = 'cargo metadata --locked --no-deps --format-version 1'
            tracked_paths_command  = 'git ls-files --cached -- *.rs'
            universe_basis_note    = 'cached tracked paths only; swarm/inventory/modules.json was generated from cached plus nonignored untracked paths, a declared drift cause alongside the exclusion profiles below'
            packages_total         = $packageIds.Count
            unique_package_rows    = $uniquePackageIds.Count
            tracked_rust_files     = $relativePaths.Count
            assigned_files         = $assignedCount
            unassigned_files       = $unassigned.Count
            excluded_files         = $excludedTotal
            excluded_outside_root_files = $unownedExcluded.Count
        }
        exclusion_profiles = [pscustomobject]@{
            matching_rule = 'exact path-component equality plus filename stem/suffix tokens split on underscore and hyphen; case-insensitive; no substring matching; categories evaluated in declared order; applied before package ownership and before any byte or STU aggregation'
            generated_code       = $ExclusionProfiles['generated_code']
            large_golden_corpora = $ExclusionProfiles['large_golden_corpora']
            vendor_source        = $ExclusionProfiles['vendor_source']
            raw_fixtures         = $ExclusionProfiles['raw_fixtures']
        }
        class_profiles = $ClassProfiles
        class_assignment_rules = @(
            'package named exactly eliot-test-support is shared test-support',
            'any package with a bin target is facade/composition/binary',
            'every other package stays UNKNOWN with null bands: no deterministic basis exists here and classes are never guessed'
        )
        unassigned_paths = @($unassigned.ToArray())
        excluded_outside_package_roots = @($unownedExcluded.ToArray())
        packages = @($records.ToArray())
        totals = [pscustomobject]@{
            crates_emitted      = $packageNames.Count
            crates_classified   = $classifiedCount
            crates_unknown      = $unknownCount
            included_files      = $totalIncluded
            excluded_files      = $excludedTotal
            unassigned_files    = $unassigned.Count
            total_included_stu  = $totalStu
        }
        invariants = [pscustomobject]@{
            blocking                  = $false
            review_semantics          = 'crossing a numeric review band records profile evidence only and never fails a crate'
            split_authority_statement = $NoSplitStatement
        }
    }

    $json = $document | ConvertTo-Json -Depth 10
    Write-Output $json
    exit 0
}
catch {
    Write-Error $_.Exception.Message
    exit 1
}
