[CmdletBinding()]
param(
    [string]$InventoryPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'swarm\inventory\contour-cut.json'),
    [string]$ResultPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'swarm\results\W1-05.json'),
    [switch]$SelfTest
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$SchemaVersion = 'eliot-contour-cut-v4'
$ResultSchemaVersion = 'eliot-w1-05-result-v4'
$MechanismReviewPath = 'swarm/challenges/W1-05-MECHANISM-REVIEW.md'
$ContourA = @('eliot-app', 'eliot-engine', 'eliot-store')
$ContourB = @('eliot', 'eliot-host', 'eliot-kernel', 'eliotd')
$UnknownProcessTarget = 'UNKNOWN_PROCESS_TARGET'
$UnknownIpcTarget = 'UNKNOWN_IPC_TARGET'
$UnknownLaunchTarget = 'UNKNOWN_LAUNCH_TARGET'
$UnknownSchemaOwner = 'UNKNOWN_SCHEMA_OWNER'
$UnknownCanonicalOwner = 'UNKNOWN_CANONICAL_OWNER'

$RegressionFixtures = @(
    [pscustomobject]@{ id = 'dynamic-command-program'; path = 'workspace/tools/eliot-runtime-compiler/src/lib.rs'; motif_id = 'process-constructor'; source_match_pattern = 'Command::new\(program\)'; expected_target = $UnknownProcessTarget; expected_source_set = 'cached' }
    [pscustomobject]@{ id = 'dynamic-command-executable'; path = 'bins/eliot-mod-research/src/lib.rs'; motif_id = 'process-constructor'; source_match_pattern = 'Command::new\(executable\)'; expected_target = $UnknownProcessTarget; expected_source_set = 'cached' }
    [pscustomobject]@{ id = 'suspended-job-spawn'; path = 'bins/eliot-host/src/lib.rs'; motif_id = 'process-wrapper-spawn'; source_match_pattern = 'SuspendedJobChild::spawn_named\('; expected_target = $UnknownProcessTarget; expected_source_set = 'cached' }
    [pscustomobject]@{ id = 'suspended-job-spawn-with-limits'; path = 'crates/instrument/eliot-process-executor/src/lib.rs'; motif_id = 'process-wrapper-spawn'; source_match_pattern = 'SuspendedJobChild::spawn_named_with_limits\('; expected_target = $UnknownProcessTarget; expected_source_set = 'cached' }
    [pscustomobject]@{ id = 'dynamic-governor-command'; path = 'crates/eliot-app/src/runtime_bootstrap.rs'; motif_id = 'process-constructor'; source_match_pattern = 'Command::new\(governor\)'; expected_target = $UnknownProcessTarget; expected_source_set = 'cached' }
    [pscustomobject]@{ id = 'bootstrap-brief'; path = 'bins/eliot/tests/bootstrap_brief.rs'; motif_id = 'process-constructor'; source_match_pattern = 'CARGO_BIN_EXE_eliot'; expected_target = 'eliot'; expected_source_set = 'cached' }
    [pscustomobject]@{ id = 'bootstrap-draft-file'; path = 'bins/eliot/src/bootstrap_draft.rs'; motif_id = $null; source_match_pattern = $null; expected_target = $null; expected_source_set = 'cached' }
)
function Fail([string]$Message) { throw "VERIFY FAILED: $Message" }
function AssertExact($Object, [string[]]$Expected, [string]$Label) { if ($null -eq $Object) { Fail "$Label is null" }; $actual=@($Object.PSObject.Properties.Name|Sort-Object);$expectedSorted=@($Expected|Sort-Object);if(($actual -join "`0") -cne ($expectedSorted -join "`0")){Fail "$Label fields differ"} }
function AssertOrdered($Object, [string[]]$Expected, [string]$Label) { if ($null -eq $Object) { Fail "$Label is null" }; $actual=@($Object.PSObject.Properties.Name);if(($actual -join "`0") -cne (@($Expected) -join "`0")){Fail "$Label field order differs"} }
function Get-Sha256([string]$Path) { return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Assert-GeneratorCliRejected([string[]]$Arguments,[string]$ExpectedPattern) {
    $psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=(Get-Command pwsh -ErrorAction Stop).Source;$psi.WorkingDirectory=$RepoRoot;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true
    foreach($argument in @('-NoProfile','-File',(Join-Path $RepoRoot 'scripts/gen-contour-cut.ps1'))+$Arguments){[void]$psi.ArgumentList.Add($argument)}
    $process=[Diagnostics.Process]::new();$process.StartInfo=$psi;if(-not $process.Start()){Fail 'could not start contour generator CLI negative fixture'};$stdout=$process.StandardOutput.ReadToEnd();$stderr=$process.StandardError.ReadToEnd();$process.WaitForExit()
    if($process.ExitCode-eq 0){Fail "contour generator CLI negative fixture unexpectedly passed: $($Arguments -join ' ')"}
    $combined=[regex]::Replace(($stdout+"`n"+$stderr),'\x1B\[[0-?]*[ -/]*[@-~]','')
    if($combined-notmatch $ExpectedPattern){Fail "contour generator CLI negative fixture returned wrong refusal for $($Arguments -join ' '): $combined"}
}
function Assert-VerifierCliRejected([string]$RejectedResultPath,[string]$ExpectedPattern) {
    $psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=(Get-Command pwsh -ErrorAction Stop).Source;$psi.WorkingDirectory=$RepoRoot;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true
    foreach($argument in @('-NoProfile','-File',(Join-Path $RepoRoot 'scripts/verify-contour-cut.ps1'),'-InventoryPath',$InventoryPath,'-ResultPath',$RejectedResultPath)){[void]$psi.ArgumentList.Add($argument)}
    $process=[Diagnostics.Process]::new();$process.StartInfo=$psi;if(-not $process.Start()){Fail 'could not start contour verifier CLI negative fixture'};$stdout=$process.StandardOutput.ReadToEnd();$stderr=$process.StandardError.ReadToEnd();$process.WaitForExit()
    if($process.ExitCode-eq 0){Fail 'contour verifier CLI negative fixture unexpectedly passed'}
    $combined=[regex]::Replace(($stdout+"`n"+$stderr),'\x1B\[[0-?]*[ -/]*[@-~]','')
    if($combined-notmatch $ExpectedPattern){Fail "contour verifier CLI negative fixture returned wrong refusal: $combined"}
}
function Get-TextSha256([string]$Text) { $sha = [Security.Cryptography.SHA256]::Create(); try { return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-', '').ToUpperInvariant() } finally { $sha.Dispose() } }
function Get-ObjectDigest($Value) { return Get-TextSha256 (($Value | ConvertTo-Json -Depth 100 -Compress)) }
function Get-RelativePath([string]$Path) { return ([IO.Path]::GetRelativePath($RepoRoot, $Path)).Replace('\', '/') }
function Get-GitRevision { $value = (& git -C $RepoRoot rev-parse HEAD 2>&1); if ($LASTEXITCODE -ne 0) { Fail "git revision failed: $value" }; return ([string]$value).Trim() }
function Get-GitPathSet([string[]]$Arguments) { $value = @(& git -C $RepoRoot @Arguments 2>&1); if ($LASTEXITCODE -ne 0) { Fail "git source-set query failed: $value" }; return @($value | ForEach-Object { ([string]$_).Trim() } | Where-Object { $_ }) }

function New-RustSourceSet([string[]]$CachedPaths, [string[]]$UntrackedPaths, [string]$Root) {
    $cached = @($CachedPaths | Where-Object { $_ } | Sort-Object -Unique); $untracked = @($UntrackedPaths | Where-Object { $_ } | Sort-Object -Unique); $union = @($cached + $untracked | Sort-Object -Unique); if ($union.Count -eq 0) { Fail 'Rust source union is empty' }
    $cachedSet = @{}; foreach ($path in $cached) { $cachedSet[[string]$path] = $true }; $kind = @{}; $bindings=@()
    foreach ($path in $union) { $absolute = Join-Path $Root $path; if (-not (Test-Path -LiteralPath $absolute -PathType Leaf)) { Fail "Rust source path is missing: $path" }; $kind[[string]$path] = if ($cachedSet.ContainsKey([string]$path)) { 'cached' } else { 'nonignored_untracked' }; $bindings += [ordered]@{path=[string]$path;sha256=Get-Sha256 $absolute} }
    return [pscustomobject]@{ Cached = @($cached); Untracked = @($untracked); Union = @($union); Kind = $kind; Bindings=@($bindings|Sort-Object path); Digest = Get-TextSha256 (($bindings | Sort-Object path | ForEach-Object { "$($_.path)`0$($_.sha256)" }) -join "`n") }
}

function Get-RustSourceSet {
    $cached = @(Get-GitPathSet @('ls-files', '--cached', '--', '*.rs')); $untracked = @(Get-GitPathSet @('ls-files', '--others', '--exclude-standard', '--', '*.rs')); return New-RustSourceSet $cached $untracked $RepoRoot
}

function Get-CargoMetadata { $raw = (& cargo metadata --format-version 1 --no-deps --manifest-path (Join-Path $RepoRoot 'Cargo.toml') 2>&1); if ($LASTEXITCODE -ne 0) { Fail "cargo metadata failed: $raw" }; $text = ($raw -join "`n").Trim(); try { $json = $text | ConvertFrom-Json } catch { Fail "cargo metadata was not JSON: $($_.Exception.Message)" }; return [pscustomobject]@{ Json = $json; Canonical = ($json | ConvertTo-Json -Depth 100 -Compress) } }
function Get-PackageRoots($Packages) { $roots = @(); foreach ($p in $Packages) { $manifest = [IO.Path]::GetFullPath([string]$p.manifest_path); $roots += [pscustomobject]@{ Name = [string]$p.name; Root = (Split-Path -Parent $manifest); Manifest = $manifest } }; return @($roots | Sort-Object { $_.Root.Length } -Descending) }
function Get-OwnerPackage([string]$RelativePath, $Roots) { $absolute = [IO.Path]::GetFullPath((Join-Path $RepoRoot $RelativePath)); foreach ($root in $Roots) { if ($absolute.StartsWith($root.Root.TrimEnd('\') + '\', [StringComparison]::OrdinalIgnoreCase)) { return $root.Name } }; return $null }
function Get-TargetMap($Packages) { $map = @{}; foreach ($p in $Packages) { foreach ($t in @($p.targets)) { if (@($t.kind) -notcontains 'bin') { continue }; foreach ($alias in @([string]$t.name, "$($t.name).exe")) { if ($alias) { $map[$alias.ToLowerInvariant()] = [string]$p.name } } } }; return $map }
function Resolve-TargetPackage([string]$Hint, [hashtable]$Map) { if ([string]::IsNullOrWhiteSpace($Hint)) { return $null }; $v = $Hint.Trim().Trim('"', "'").ToLowerInvariant(); if ($Map.ContainsKey($v)) { return $Map[$v] }; if ($v.EndsWith('.exe') -and $Map.ContainsKey($v.Substring(0, $v.Length - 4))) { return $Map[$v.Substring(0, $v.Length - 4)] }; if ($Map.ContainsKey("$v.exe")) { return $Map["$v.exe"] }; return $null }
function Get-NearestSymbol($Lines, [int]$Index) { for ($i = $Index; $i -ge [Math]::Max(0, $Index - 100); $i--) { if ($Lines[$i] -match '^\s*(?:(?:pub)(?:\([^)]*\))?\s+)?(?:(?:async)\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)') { return [pscustomobject]@{ Name = $Matches[1]; Text = $Lines[$i].Trim() } } }; return [pscustomobject]@{ Name = 'module_scope'; Text = '<module-scope>' } }

function Get-Grammar {
    return @(
        [pscustomobject]@{ id = 'runtime-executable-literal'; pattern = '(?i)\b(?<target>eliot(?:-governor|-host|-kernel|d)(?:\.exe)?)\b'; edge_class = 'runtime_process_observation'; resolver = 'literal'; kind = 'process'; semantics = 'literal executable/process identity' }
        [pscustomobject]@{ id = 'process-constructor'; pattern = '(?i)(?<constructor>(?:(?:std|tokio)::process::)?(?:Command|StdCommand|ProcessCommand|TokioCommand|TokioProcessCommand|AsyncCommand))\s*::\s*new\s*\('; edge_class = 'process_launch_observation'; resolver = 'constructor'; kind = 'process'; semantics = 'qualified/dynamic process constructor; target may remain unknown' }
        [pscustomobject]@{ id = 'process-literal-launch'; pattern = '(?i)(?:(?:std|tokio)::process::)?(?:Command|StdCommand|ProcessCommand|TokioCommand|TokioProcessCommand|AsyncCommand)\s*::\s*new\s*\(\s*"(?<target>[^"]+)"'; edge_class = 'process_launch_observation'; resolver = 'literal'; kind = 'process'; semantics = 'literal process constructor target' }
        [pscustomobject]@{ id = 'process-wrapper-spawn'; pattern = '(?i)\bSuspendedJobChild::spawn_named(?:_with_limits)?\s*\('; edge_class = 'process_wrapper_observation'; resolver = 'unknown'; kind = 'process'; semantics = 'Windows suspended process wrapper operation' }
        [pscustomobject]@{ id = 'process-executor-wrapper'; pattern = '(?i)\b(?:WindowsProcessExecutor|ProcessExecutor|ProcessRequest|ProcessIntent|ProcessStartReceipt|ProcessExecutionAdmissionRequest)\b'; edge_class = 'process_wrapper_observation'; resolver = 'unknown'; kind = 'process'; semantics = 'process-executor wrapper/contract symbol; target remains unknown' }
        [pscustomobject]@{ id = 'windows-process-api'; pattern = '(?i)\b(?:CreateProcess(?:A|W)?|CreateProcessAsUser(?:A|W)?|CreateProcessWithTokenW|CreateProcessWithLogonW)\s*\('; edge_class = 'process_wrapper_observation'; resolver = 'unknown'; kind = 'process'; semantics = 'Windows process API operation' }
        [pscustomobject]@{ id = 'runtime-launch-contract'; pattern = '\b(?<symbol>EliotdLaunchDescriptor|HostStoreBootstrapRequirement|KernelLaunchBinding|launch_nonce|store-bootstrap|eliotd-descriptor)\b'; edge_class = 'launch_control_observation'; resolver = 'unknown'; kind = 'launch'; semantics = 'launch/control contract motif; endpoint remains unknown' }
        [pscustomobject]@{ id = 'ipc-named-pipe-operation'; pattern = '(?i)\b(?<owner>NamedPipeTransport|NamedPipeServer|NamedPipeClient|NamedPipeIpcServer|ClientOptions|ServerOptions|PipeClient|PipeServer)\s*(?:::|\.)\s*(?<operation>connect_authenticated|connect|create|new|open|listen|accept|send_frame|receive_frame)\b'; edge_class = 'runtime_ipc_observation'; resolver = 'unknown'; kind = 'ipc'; semantics = 'named-pipe client/server/transport operation' }
        [pscustomobject]@{ id = 'ipc-qualified-named-pipe-api'; pattern = '(?i)\b(?:tokio::net::windows::named_pipe::(?:ClientOptions|ServerOptions)|windows_sys::Win32::System::Pipes::[A-Za-z0-9_]+)\b'; edge_class = 'runtime_ipc_observation'; resolver = 'unknown'; kind = 'ipc'; semantics = 'qualified named-pipe API symbol' }
        [pscustomobject]@{ id = 'ipc-peer-auth'; pattern = '(?i)\b(?:observe_named_pipe_peer_process(?:_in_job)?|authenticate_named_pipe_(?:server|client)|current_process_named_pipe_expectation)\s*\('; edge_class = 'runtime_ipc_observation'; resolver = 'unknown'; kind = 'ipc'; semantics = 'named-pipe peer identity/authentication operation' }
        [pscustomobject]@{ id = 'ipc-transport-symbol'; pattern = '\b(?:NamedPipeTransport|NamedPipeServer|NamedPipeIpcServer|NamedPipeClient|NamedPipePeerExpectation|KernelClient|DaemonKernelClient|IpcGovernorClient|HookIpcForwarder)\b'; edge_class = 'runtime_ipc_observation'; resolver = 'unknown'; kind = 'ipc'; semantics = 'IPC transport/client/server symbol' }
        [pscustomobject]@{ id = 'ipc-handshake-symbol'; pattern = '\b(?:connect_authenticated|handshake_rejection_frame|server_hello_frame|client_hello_frame|client_hello|server_hello)\b'; edge_class = 'runtime_ipc_observation'; resolver = 'unknown'; kind = 'ipc'; semantics = 'IPC handshake/frame symbol' }
        [pscustomobject]@{ id = 'ipc-host-governor-request'; pattern = '\b(?:host_governor_request|IpcGovernorClient)\s*\('; edge_class = 'runtime_ipc_observation'; resolver = 'unknown'; kind = 'ipc'; semantics = 'host/governor IPC request operation' }
        [pscustomobject]@{ id = 'contract-governor-config'; pattern = '\bGovernorConfig\b'; edge_class = 'shared_contract_type'; resolver = 'fixed:eliot-types'; kind = 'contract'; semantics = 'GovernorConfig import/parse/type use; not a runtime join' }
        [pscustomobject]@{ id = 'contract-runtime-contracts'; pattern = '(?i)\b(?:eliot_runtime_contracts|eliot-runtime-contracts)\b'; edge_class = 'shared_contract_type'; resolver = 'fixed:eliot-runtime-contracts'; kind = 'contract'; semantics = 'runtime contract package reference' }
        [pscustomobject]@{ id = 'state-write-receipt'; pattern = '\b(?:write_receipt|write_receipt_by_id)\b'; edge_class = 'state_write_observation'; resolver = 'unknown'; kind = 'state'; semantics = 'write receipt symbol; owner/route is not inferred' }
        [pscustomobject]@{ id = 'schema-version-field'; pattern = '\bschema_version\b'; edge_class = 'schema_observation'; resolver = 'fixed:UNKNOWN_SCHEMA_OWNER'; kind = 'schema'; semantics = 'schema/version field only; never write authority' }
        [pscustomobject]@{ id = 'canonical-write-symbol'; pattern = '\bcommit_canonical\s*\('; edge_class = 'canonical_write_observation'; resolver = 'fixed:eliot-governor'; kind = 'canonical'; semantics = 'canonical write definition/reference; exact caller proof is separate' }
    )
}

function Get-Contour([string]$Package) { if ($Package -in $ContourA) { return 'A' }; if ($Package -in $ContourB) { return 'B' }; return $null }
function Get-Direction([string]$From, [string]$To) { $a = Get-Contour $From; $b = Get-Contour $To; if ($a -and $b -and $a -ne $b) { return "${a}_TO_${b}" }; if ($a -and $b) { return "${a}_INTRA" }; if ($a) { return "${a}_TO_SHARED_OR_UNKNOWN" }; if ($b) { return "EXTERNAL_TO_${b}" }; return 'EXTERNAL_OR_UNKNOWN' }
function Get-MotifRole([string]$Id, [string]$Line) { $s = $Line.Trim(); if ($Id -eq 'contract-governor-config') { if ($s -match '^use\b|^pub\s+use\b') { return 'import' }; if ($s -match '(?i)from_str|from_slice|deserialize|toml') { return 'parse' }; return 'type_reference' }; if ($Id -eq 'canonical-write-symbol') { if ($s -match '^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn\s+commit_canonical\s*\(') { return 'definition' }; return 'reference' }; return 'observation' }

function Get-TargetEvidence($Motif, $Match, [string]$Line, [hashtable]$TargetMap) {
    $hint = $null; $resolution = 'unknown_dynamic_target'
    if ($Motif.resolver -like 'fixed:*') { return [pscustomobject]@{ Target = $Motif.resolver.Substring(6); Resolution = 'fixed_owner' } }
    if ($Motif.resolver -eq 'literal' -and $Match.Groups['target'].Success) { $hint = $Match.Groups['target'].Value; $resolution = 'literal_target' }
    elseif ($Motif.resolver -eq 'constructor') { $argument = [regex]::Match($Line, '(?i)::\s*new\s*\(\s*(?<argument>[^,\)]*)').Groups['argument'].Value.Trim(); $envMatch = [regex]::Match($argument, '(?i)env!\s*\(\s*"CARGO_BIN_EXE_(?<bin>[^"]+)"'); if ($envMatch.Success) { $hint = $envMatch.Groups['bin'].Value; $resolution = 'cargo_bin_env_target' } elseif ($argument -match '^"(?<literal>[^"]+)"$') { $hint = $Matches['literal']; $resolution = 'literal_target' } }
    $target = Resolve-TargetPackage $hint $TargetMap; if ($target) { return [pscustomobject]@{ Target = $target; Resolution = $resolution } }; return [pscustomobject]@{ Target = $UnknownProcessTarget; Resolution = if ($resolution -eq 'literal_target') { 'unknown_literal_target' } else { $resolution } }
}

function New-ExpectedRow($Values) {
    return [pscustomobject]@{ id = $Values.id; from = $Values.from; to = $Values.to; edge_class = $Values.edge_class; relation = $Values.relation; direction = $Values.direction; motif_id = $Values.motif_id; source_path = $Values.source_path; source_line = $Values.source_line; source_symbol = $Values.source_symbol; source_symbol_text = $Values.source_symbol_text; source_pattern = $Values.source_pattern; source_match_text = $Values.source_match_text; source_file_sha256 = $Values.source_file_sha256; source_symbol_sha256 = if ($null -eq $Values.source_symbol_text) { $null } else { Get-TextSha256 ([string]$Values.source_symbol_text) }; source_match_sha256 = if ($null -eq $Values.source_match_text) { $null } else { Get-TextSha256 ([string]$Values.source_match_text) }; source_file_set = $Values.source_file_set; target_resolution = $Values.target_resolution; status = $Values.status; severity = $Values.severity; join_claim = $false; falsifier = $Values.falsifier }
}

function Get-ExpectedCensus($SourceSet, $Roots, [hashtable]$TargetMap) {
    $rows = New-Object 'System.Collections.Generic.List[object]'; $hitCounts = [ordered]@{}; $rowCounts = [ordered]@{}; $motifs = @(Get-Grammar); $compiled = @{}; $cache = @{}; $symbolCache = @{}
    foreach ($motif in $motifs) { $compiled[$motif.id] = [regex]::new([string]$motif.pattern); $hitCounts[$motif.id] = 0; $rowCounts[$motif.id] = 0 }
    foreach ($relative in $SourceSet.Union) {
        $path = Join-Path $RepoRoot $relative; if (-not $cache.ContainsKey($relative)) { $cache[$relative] = [pscustomobject]@{ Lines = @(Get-Content -LiteralPath $path); Hash = Get-Sha256 $path; Owner = Get-OwnerPackage $relative $Roots } }; $entry = $cache[$relative]
        for ($lineIndex = 0; $lineIndex -lt $entry.Lines.Count; $lineIndex++) {
            $line = [string]$entry.Lines[$lineIndex]
            foreach ($motif in $motifs) {
                $matches = $compiled[$motif.id].Matches($line); if ($matches.Count -eq 0) { continue }; $hitCounts[$motif.id] += $matches.Count
                foreach ($match in $matches) {
                    $owner = if ($entry.Owner) { [string]$entry.Owner } else { 'UNOWNED' }; $targetInfo = Get-TargetEvidence $motif $match $line $TargetMap; $to = $targetInfo.Target; $role = Get-MotifRole $motif.id $line; $edge = [string]$motif.edge_class; $relation = 'non_join'; $status = 'unknown'; $severity = 'medium'; $falsifier = 'A source motif is evidence only; prove an authenticated invoked process/IPC path before calling it a contour join.'
                    if ($motif.kind -eq 'process') {
                        $status = 'present'; $severity = 'high'; $relation = if ($to -eq $UnknownProcessTarget) { 'dynamic_or_unresolved_process_observation' } else { 'launch_candidate' }
                        if ($motif.id -eq 'runtime-executable-literal' -and $to -eq 'eliot-app' -and $line -match '(?i)legacy|any_running_process_named|process state|already running|is running|coexist|retire') { $edge = 'negative_observation'; $relation = 'non_join'; $severity = 'high'; $falsifier = 'Find an actual process launch or IPC invocation; a negative coexistence check is not a runtime join.' }
                        elseif ($motif.id -eq 'runtime-executable-literal') { $edge = 'runtime_process_observation'; $relation = if ($to -eq $UnknownProcessTarget) { 'unresolved_process_observation' } else { 'intra_or_external_process_observation' }; $status = if ($to -eq $UnknownProcessTarget) { 'unknown' } else { 'present' }; $severity = if ($to -eq $UnknownProcessTarget) { 'medium' } else { 'high' }; $falsifier = 'A process-name literal is not proof of a launch, IPC connection, or contour join.' }
                        elseif ($motif.id -like 'process-wrapper*' -or $motif.id -eq 'process-executor-wrapper' -or $motif.id -eq 'windows-process-api') { $edge = 'process_wrapper_observation'; $relation = 'process_wrapper_operation'; $to = $UnknownProcessTarget; $targetInfo = [pscustomobject]@{ Target = $to; Resolution = 'explicit_unknown_process_wrapper' }; $falsifier = 'Resolve the concrete executable and authenticated invocation; a process wrapper symbol alone is not runtime proof.' }
                        elseif ($motif.id -eq 'process-literal-launch' -or $motif.id -eq 'process-constructor') { $edge = 'process_launch_observation'; $falsifier = if ($to -eq $UnknownProcessTarget) { 'Resolve the dynamic process target and show authenticated protocol completion; constructor evidence alone is not runtime success.' } else { 'Show the launched process reaches the target contour and completes an authenticated protocol; construction alone does not prove runtime success.' } }
                    } elseif ($motif.kind -eq 'ipc') { $edge = 'runtime_ipc_observation'; $relation = 'ipc_operation'; $status = 'present'; $severity = 'high'; $to = $UnknownIpcTarget; $targetInfo = [pscustomobject]@{ Target = $to; Resolution = 'explicit_unknown_ipc_endpoint' }; $falsifier = 'Show the named-pipe endpoint, authenticated peer, and invoked protocol; symbol/operation evidence alone is not a contour join.'
                    } elseif ($motif.kind -eq 'launch') { $edge = 'launch_control_observation'; $relation = 'launch_contract_symbol'; $status = 'unknown'; $severity = 'high'; $to = $UnknownLaunchTarget; $targetInfo = [pscustomobject]@{ Target = $to; Resolution = 'explicit_unknown_launch_endpoint' }; $falsifier = 'Resolve the launch endpoint and prove an invoked authenticated process path; launch/control contract symbols alone are not a join.'
                    } elseif ($motif.id -eq 'contract-governor-config') { $edge = 'shared_contract_type'; $relation = "type_$role"; $status = 'present'; $severity = 'low'; $falsifier = 'A GovernorConfig import or parse is not a runtime join; require a resolved process/IPC call and independent trace.'
                    } elseif ($motif.id -eq 'contract-runtime-contracts') { $edge = 'shared_contract_type'; $relation = 'contract_reference'; $status = 'present'; $severity = 'low'; $falsifier = 'A contract package reference does not prove runtime connection or authority ownership.'
                    } elseif ($motif.id -eq 'schema-version-field') { $edge = 'schema_observation'; $relation = 'non_join'; $status = 'unknown'; $severity = 'low'; $to = $UnknownSchemaOwner; $targetInfo = [pscustomobject]@{ Target = $to; Resolution = 'explicit_unknown_schema_owner' }; $falsifier = 'A schema_version field alone cannot establish a write authority or contour join.'
                    } elseif ($motif.id -eq 'state-write-receipt') { $edge = 'state_write_observation'; $relation = 'write_symbol_only'; $status = 'unknown'; $severity = 'high'; $to = $UnknownCanonicalOwner; $targetInfo = [pscustomobject]@{ Target = $to; Resolution = 'explicit_unknown_canonical_owner' }; $falsifier = 'Identify the single invoked canonical owner and authenticated route; a write_receipt symbol is not proof of ownership.'
                    } elseif ($motif.id -eq 'canonical-write-symbol') { $edge = if ($role -eq 'definition') { 'canonical_write_definition' } else { 'canonical_write_reference' }; $relation = $role; $status = 'present'; $severity = 'critical'; $to = 'eliot-governor'; $targetInfo = [pscustomobject]@{ Target = $to; Resolution = 'fixed_owner' }; $falsifier = 'The separate commit_canonical proof must show exactly one definition and zero callers across the cached plus non-ignored-untracked Rust union.' }
                    if (-not $symbolCache.ContainsKey("$relative`:$($lineIndex + 1)")) { $symbolCache["$relative`:$($lineIndex + 1)"] = Get-NearestSymbol $entry.Lines $lineIndex }; $symbol = $symbolCache["$relative`:$($lineIndex + 1)"]; $safeTo = if ($to) { [string]$to } else { 'UNRESOLVED' }; $id = "CENSUS-$($motif.id)-$owner-$safeTo-$($relative.Replace('/','_').Replace('.','_'))-L$($lineIndex + 1)-$($match.Index)"
                    $null = $rows.Add([object](New-ExpectedRow @{ id = $id; from = $owner; to = $safeTo; edge_class = $edge; relation = $relation; direction = Get-Direction $owner $safeTo; motif_id = $motif.id; source_path = $relative; source_line = $lineIndex + 1; source_symbol = $symbol.Name; source_symbol_text = $symbol.Text; source_pattern = $motif.pattern; source_match_text = $line.Trim(); source_file_sha256 = $entry.Hash; source_file_set = $SourceSet.Kind[$relative]; target_resolution = $targetInfo.Resolution; status = $status; severity = $severity; falsifier = $falsifier })); $rowCounts[$motif.id] += 1
                }
            }
        }
    }
    return [pscustomobject]@{ Rows = $rows.ToArray(); HitCounts = $hitCounts; RowCounts = $rowCounts; HitCount = @($hitCounts.Values | Measure-Object -Sum).Sum; RowCount = $rows.Count }
}

function Get-ManifestDependencyLine($Package, [string]$Name) { $lines = @(Get-Content -LiteralPath ([string]$Package.manifest_path)); for ($i = 0; $i -lt $lines.Count; $i++) { if ($lines[$i] -match ('^\s*' + [regex]::Escape($Name) + '\s*=')) { return $i + 1 } }; return $null }
function Get-ManifestEvidence($Package, [string]$Name) { $line = Get-ManifestDependencyLine $Package $Name; $path = [string]$Package.manifest_path; $text = if ($null -eq $line) { $null } else { (Get-Content -LiteralPath $path)[$line - 1].Trim() }; return [pscustomobject]@{ source_path = Get-RelativePath $path; source_line = $line; source_symbol = '[dependencies]'; source_symbol_text = $text; source_pattern = '^\s*' + [regex]::Escape($Name) + '\s*='; source_file_sha256 = Get-Sha256 $path } }

function Get-ExpectedCargoRows($Metadata) {
    $by = @{}; foreach ($p in $Metadata.Json.packages) { $by[[string]$p.name] = $p }; foreach ($name in ($ContourA + $ContourB)) { if (-not $by.ContainsKey($name)) { Fail "missing package $name" } }; $rows = @()
    foreach ($from in ($ContourA + $ContourB)) { $fc = Get-Contour $from; $targets = if ($fc -eq 'A') { $ContourB } else { $ContourA }; $direction = if ($fc -eq 'A') { 'A_TO_B' } else { 'B_TO_A' }; foreach ($to in $targets) { $package = $by[$from]; $present = @($package.dependencies | Where-Object { $_.name -eq $to -and $null -eq $_.source }).Count -gt 0; $e = Get-ManifestEvidence $package $to; $status = if ($present) { 'present' } else { 'absent' }; $match = if ($present) { $e.source_symbol_text } else { $null }; $severity = if ($present) { 'critical' } else { 'info' }; $falsifier = if ($present) { 'Recompute cargo metadata and remove the direct path dependency.' } else { 'A direct path dependency in cargo metadata falsifies absence.' }; $rows += ,(New-ExpectedRow @{ id = "CARGO-$from-to-$to"; from = $from; to = $to; edge_class = 'cargo_dependency'; relation = 'cargo_direct_dependency'; direction = $direction; motif_id = 'cargo-metadata'; source_path = $e.source_path; source_line = $e.source_line; source_symbol = $e.source_symbol; source_symbol_text = $e.source_symbol_text; source_pattern = $e.source_pattern; source_match_text = $match; source_file_sha256 = $e.source_file_sha256; source_file_set = 'cargo-manifest'; target_resolution = 'cargo_metadata_direct_edge'; status = $status; severity = $severity; falsifier = $falsifier }) } }
    $aDeps = @($ContourA | ForEach-Object { @($by[$_].dependencies | Where-Object { $null -eq $_.source } | ForEach-Object name) } | Sort-Object -Unique); $bDeps = @($ContourB | ForEach-Object { @($by[$_].dependencies | Where-Object { $null -eq $_.source } | ForEach-Object name) } | Sort-Object -Unique); $shared = @($aDeps | Where-Object { $_ -in $bDeps -and $_ -match '(?i)(contract|type|protocol|receipt|state|config)' } | Sort-Object); foreach ($name in $shared) { foreach ($from in ($ContourA + $ContourB)) { if (@($by[$from].dependencies | Where-Object { $_.name -eq $name -and $null -eq $_.source }).Count -eq 0) { continue }; $e = Get-ManifestEvidence $by[$from] $name; $contour = Get-Contour $from; $rows += ,(New-ExpectedRow @{ id = "SHARED-$from-to-$name"; from = $from; to = $name; edge_class = 'shared_contract_type'; relation = 'cargo_shared_dependency'; direction = "${contour}_TO_SHARED"; motif_id = 'cargo-metadata'; source_path = $e.source_path; source_line = $e.source_line; source_symbol = $e.source_symbol; source_symbol_text = $e.source_symbol_text; source_pattern = $e.source_pattern; source_match_text = $e.source_symbol_text; source_file_sha256 = $e.source_file_sha256; source_file_set = 'cargo-manifest'; target_resolution = 'cargo_metadata_shared_dependency'; status = 'present'; severity = 'medium'; falsifier = 'Remove the direct shared dependency or demonstrate it is not a contract/type package.' }) } }
    return @($rows)
}

function Get-ExpectedProof($SourceSet, $Roots) { $definitions = @(); $callers = @(); $ref = '\bcommit_canonical\s*\('; $def = '^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn\s+commit_canonical\s*\('; foreach ($relative in $SourceSet.Union) { $path = Join-Path $RepoRoot $relative; $lines = @(Get-Content -LiteralPath $path); $hash = Get-Sha256 $path; for ($i = 0; $i -lt $lines.Count; $i++) { if ($lines[$i] -notmatch $ref) { continue }; $symbol = Get-NearestSymbol $lines $i; $e = [pscustomobject]@{ source_path = $relative; source_line = $i + 1; source_symbol = $symbol.Name; source_symbol_text = $symbol.Text; source_match_text = $lines[$i].Trim(); source_file_sha256 = $hash; source_symbol_sha256 = Get-TextSha256 $symbol.Text; source_match_sha256 = Get-TextSha256 $lines[$i].Trim(); source_file_set = $SourceSet.Kind[$relative]; package = Get-OwnerPackage $relative $Roots }; if ($lines[$i] -match $def) { $definitions += ,$e } else { $callers += ,$e } } }; return [ordered]@{ symbol = 'commit_canonical'; source_file_set_kind = 'git_cached_plus_nonignored_untracked_rust'; rust_file_count = $SourceSet.Union.Count; definition_pattern = $def; reference_pattern = $ref; definition_count = $definitions.Count; caller_count = $callers.Count; definitions = @($definitions | Sort-Object source_path, source_line); callers = @($callers | Sort-Object source_path, source_line); status = if ($definitions.Count -eq 1 -and $callers.Count -eq 0) { 'VERIFIED_ONE_DEFINITION_ZERO_CALLERS' } else { 'FALSIFIED' }; falsifier = 'Any second definition or any non-definition commit_canonical reference in the cached plus non-ignored-untracked Rust union falsifies this §5.1 proof.' } }

function Assert-ExactRows($Actual, $Expected, [string]$Label) { $aIds = @($Actual | ForEach-Object id); $eIds = @($Expected | ForEach-Object id); $missing = @($eIds | Where-Object { $_ -notin $aIds }); $extra = @($aIds | Where-Object { $_ -notin $eIds }); if ($missing.Count -gt 0 -or $extra.Count -gt 0) { if ($Label -eq 'census') { Fail "omitted/discoverable census edge mismatch: missing=$($missing -join ',') extra=$($extra -join ',')" }; Fail "$Label row mismatch: missing=$($missing -join ',') extra=$($extra -join ',')" }; $byId = @{}; foreach ($row in $Actual) { $byId[$row.id] = $row }; $fields = @('id','from','to','edge_class','relation','direction','motif_id','source_path','source_line','source_symbol','source_symbol_text','source_pattern','source_match_text','source_file_sha256','source_symbol_sha256','source_match_sha256','source_file_set','target_resolution','status','severity','join_claim','falsifier'); foreach ($row in $Expected) { $got = $byId[$row.id]; AssertOrdered $got $fields "$Label row $($row.id)"; foreach ($field in $fields) { if ([string]$got.$field -cne [string]$row.$field) { Fail "$Label field drift for $($row.id): $field" } } } }
function Assert-SourceSet($Inventory, $SourceSet) { $scan = $Inventory.source_scan; if ($scan.file_set_kind -ne 'git_cached_plus_nonignored_untracked_rust' -or $scan.provenance -ne 'content_bound_path_plus_bytes' -or $scan.grammar_file_set -ne 'direct-read-source-union') { Fail 'source-set declaration drift' }; if ([int]$scan.cached_rust_file_count -ne $SourceSet.Cached.Count -or [int]$scan.nonignored_untracked_rust_file_count -ne $SourceSet.Untracked.Count -or [int]$scan.union_rust_file_count -ne $SourceSet.Union.Count) { Fail 'source-set count drift' }; if ((@($scan.rust_files) -join '|') -cne ($SourceSet.Union -join '|')) { Fail 'source-set path union drift' }; if ((@($scan.nonignored_untracked_rust_files) -join '|') -cne ($SourceSet.Untracked -join '|')) { Fail 'untracked source-set drift' }; $stored=@{}; foreach($b in @($scan.rust_file_bindings)){$stored[[string]$b.path]=[string]$b.sha256}; foreach($b in @($SourceSet.Bindings)){if(-not $stored.ContainsKey([string]$b.path) -or $stored[[string]$b.path] -cne [string]$b.sha256){Fail "content-bound source binding drift: $($b.path)"}}; if ($stored.Count -ne $SourceSet.Bindings.Count) { Fail 'content-bound source binding count drift' }; if ([string]$scan.rust_files_sha256 -cne [string]$SourceSet.Digest) { Fail 'source-set digest drift' }; if ($scan.completeness_statement -ne 'COMPLETE_CURRENT_FILE_SET_DECLARED_GRAMMAR_ONLY' -or $scan.semantic_exhaustiveness_claim -ne $false) { Fail 'semantic-exhaustiveness claim drift' } }
function Assert-SourceEvidence($Inventory, $SourceSet) { $cache = @{}; foreach ($row in @($Inventory.rows)) { $path = Join-Path $RepoRoot ([string]$row.source_path); if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { Fail "source path missing $($row.id)" }; if (-not $cache.ContainsKey($row.source_path)) { $cache[$row.source_path] = [pscustomobject]@{ Hash = Get-Sha256 $path; Lines = @(Get-Content -LiteralPath $path) } }; $entry = $cache[$row.source_path]; if ($entry.Hash -cne [string]$row.source_file_sha256) { Fail "source digest stale $($row.id)" }; if ($row.source_file_set -eq 'cargo-manifest') { if ($row.motif_id -ne 'cargo-metadata') { Fail "non-Cargo row marked cargo-manifest $($row.id)" } } else { if ($row.source_file_set -notin @('cached','nonignored_untracked')) { Fail "source-file-set field invalid $($row.id)" }; if (-not $SourceSet.Kind.ContainsKey([string]$row.source_path)) { Fail "source path is outside bound source union $($row.id)" }; if ([string]$SourceSet.Kind[[string]$row.source_path] -cne [string]$row.source_file_set) { Fail "source stage classification drift $($row.id)" } }; if ($null -eq $row.source_line) { if ($null -ne $row.source_match_text -or $null -ne $row.source_symbol_text -or $null -ne $row.source_match_sha256 -or $null -ne $row.source_symbol_sha256) { Fail "null source anchor fields drift $($row.id)" }; continue }; $lineNumber = [int]$row.source_line; if ($lineNumber -lt 1 -or $lineNumber -gt $entry.Lines.Count) { Fail "source line out of range $($row.id)" }; $line = ([string]$entry.Lines[$lineNumber - 1]).Trim(); if ([string]$line -cne [string]$row.source_match_text) { Fail "source match text stale $($row.id)" }; $matchHash = Get-TextSha256 $line; if ($matchHash -cne [string]$row.source_match_sha256) { Fail "source match digest stale $($row.id)" }; if ($row.motif_id -ne 'cargo-metadata') { $symbol = Get-NearestSymbol $entry.Lines ($lineNumber - 1); if ([string]$symbol.Name -cne [string]$row.source_symbol -or [string]$symbol.Text -cne [string]$row.source_symbol_text) { Fail "source symbol anchor stale $($row.id)" } }; if ($null -ne $row.source_symbol_text) { $symbolHash = Get-TextSha256 ([string]$row.source_symbol_text); if ($symbolHash -cne [string]$row.source_symbol_sha256) { Fail "source symbol digest stale $($row.id)" } } } }
function Assert-Basic($Inventory) { if ($Inventory.schema_version -ne $SchemaVersion -or $Inventory.authority_status -ne 'EVIDENCE_ONLY') { Fail 'schema/authority mismatch' }; if ($Inventory.cutover_decision.selected -ne $null -or $Inventory.cutover_decision.status -ne 'PENDING_ROOT') { Fail 'cutover selected by inventory' }; if ($Inventory.source_scan.completeness_statement -ne 'COMPLETE_CURRENT_FILE_SET_DECLARED_GRAMMAR_ONLY' -or $Inventory.source_scan.semantic_exhaustiveness_claim -ne $false) { Fail 'semantic-exhaustiveness declaration drift' }; $rows = @($Inventory.rows); $ids = @($rows | ForEach-Object id); if (@($ids | Sort-Object -Unique).Count -ne $ids.Count) { Fail 'rows duplicated' }; $sorted = @($rows | Sort-Object edge_class,direction,from,to,id); if ((@($sorted | ForEach-Object id) -join '|') -cne ($ids -join '|')) { Fail 'row order noncanonical' }; foreach ($row in $rows) { if ($row.join_claim -ne $false) { Fail "runtime join claimed by $($row.id)" }; if ($row.status -notin @('present','absent','unknown')) { Fail "invalid status $($row.id)" }; if ($row.edge_class -eq 'negative_observation' -and ($row.relation -ne 'non_join' -or $row.join_claim -ne $false)) { Fail 'negative observation mislabeled as join' }; if ($row.motif_id -eq 'schema-version-field' -and $row.edge_class -ne 'schema_observation') { Fail 'schema row mislabeled state authority' }; if ($row.motif_id -eq 'contract-governor-config' -and [string]$row.relation -notmatch '^type_(import|parse|type_reference)$') { Fail 'GovernorConfig role is not import/parse/type-only' }; if ($row.to -eq $UnknownProcessTarget -and $row.status -eq 'absent') { Fail 'unknown process target cannot be absent' }; if ($row.to -eq $UnknownIpcTarget -and $row.status -eq 'absent') { Fail 'unknown IPC target cannot be absent' } } }
function Assert-RegressionFixtures($Inventory, $SourceSet) { $actual = @($Inventory.source_scan.regression_fixtures); if ($actual.Count -ne $RegressionFixtures.Count) { Fail 'regression fixture count drift' }; foreach ($fixture in $RegressionFixtures) { $got = @($actual | Where-Object id -eq $fixture.id); if ($got.Count -ne 1) { Fail "regression fixture missing $($fixture.id)" }; if ($got[0].path -ne $fixture.path -or $got[0].motif_id -cne $fixture.motif_id -or $got[0].source_set -cne $fixture.expected_source_set) { Fail "regression fixture field/stage drift $($fixture.id)" }; if (-not $SourceSet.Kind.ContainsKey([string]$fixture.path) -or [string]$SourceSet.Kind[[string]$fixture.path] -cne [string]$fixture.expected_source_set) { Fail "regression fixture source stage drift $($fixture.id)" }; $full=Join-Path $RepoRoot $fixture.path; if ((Get-Sha256 $full) -cne [string]$got[0].source_file_sha256) { Fail "regression fixture content drift $($fixture.id)" }; if ($fixture.motif_id -and $got[0].target -ne $fixture.expected_target) { Fail "regression fixture target drift $($fixture.id)" } }; if (@($SourceSet.Union).Count -eq 0) { Fail 'Rust regression source missing' } }

function Assert-CargoRows($Inventory, $Metadata) { $expected = @(Get-ExpectedCargoRows $Metadata); $actual = @($Inventory.rows | Where-Object { $_.motif_id -eq 'cargo-metadata' -and $_.edge_class -in @('cargo_dependency','shared_contract_type') }); Assert-ExactRows $actual $expected 'Cargo'; $digest = Get-TextSha256 $Metadata.Canonical; if ($digest -cne [string]$Inventory.cargo_metadata_sha256) { Fail 'cargo metadata digest stale' } }
function Assert-CanonicalProof($Inventory, $Expected) { $got = $Inventory.canonical_write_proof; if ((Get-ObjectDigest $got) -cne (Get-ObjectDigest $Expected)) { Fail 'commit_canonical proof drift' }; if ($Expected.definition_count -ne 1 -or $Expected.caller_count -ne 0) { Fail '§5.1 exact commit_canonical proof is falsified' }; if (@($got.definitions).Count -ne 1 -or @($Expected.definitions).Count -ne 1) { Fail 'commit_canonical definition evidence missing' }; if (@($got.callers).Count -ne 0) { Fail 'commit_canonical caller list is non-empty' } }

function Get-JsonBytes($Value) { return [Text.UTF8Encoding]::new($false).GetBytes(($Value | ConvertTo-Json -Depth 100) + "`n") }

function Get-ExpectedResultProjection($Inventory) {
    $rows = @($Inventory.rows); $scan = $Inventory.source_scan; $summary = $Inventory.summary; $proof = $Inventory.canonical_write_proof
    return [ordered]@{
        disposition = 'IMPLEMENTED'
        contour_a = @($Inventory.contours.A)
        contour_b = @($Inventory.contours.B)
        rows = [int]$summary.row_count
        cargo_direct_edges = [ordered]@{
            A_TO_B = [ordered]@{ present = @($rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'A_TO_B' -and $_.status -eq 'present' }).Count; absent = @($rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'A_TO_B' -and $_.status -eq 'absent' }).Count }
            B_TO_A = [ordered]@{ present = @($rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'B_TO_A' -and $_.status -eq 'present' }).Count; absent = @($rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'B_TO_A' -and $_.status -eq 'absent' }).Count }
        }
        source_scan = [ordered]@{
            file_set_kind = $scan.file_set_kind; grammar_file_set = $scan.grammar_file_set; cached_rust_file_count = [int]$scan.cached_rust_file_count
            nonignored_untracked_rust_file_count = [int]$scan.nonignored_untracked_rust_file_count; union_rust_file_count = [int]$scan.union_rust_file_count
            grammar_motifs = @($scan.grammar).Count; hit_count = $scan.hit_count; row_count = [int]$scan.row_count
            motif_hit_counts = $scan.motif_hit_counts; motif_row_counts = $scan.motif_row_counts; provenance = $scan.provenance; rust_files_sha256 = $scan.rust_files_sha256
        }
        edge_class_counts = $summary.edge_class_counts
        status_counts = $summary.status_counts
        semantic_counts = [ordered]@{
            negative_observation_non_join = [int]$summary.negative_observation_non_join; process_launch_observation = [int]$summary.process_launch_observation
            process_wrapper_observation = [int]$summary.process_wrapper_observation; runtime_ipc_observation = [int]$summary.runtime_ipc_observation
            launch_control_observation = [int]$summary.launch_control_observation; schema_observation = [int]$summary.schema_observation
            state_write_unknown = [int]$summary.state_write_unknown; unknown_process_target = [int]$summary.unknown_process_target
            unknown_ipc_target = [int]$summary.unknown_ipc_target; unknown_launch_target = [int]$summary.unknown_launch_target
            present = [int]$summary.status_counts.present; absent = [int]$summary.status_counts.absent; unknown = [int]$summary.status_counts.unknown
        }
        regression_fixtures = @($scan.regression_fixtures)
        canonical_write_proof = [ordered]@{ symbol = $proof.symbol; source_file_set_kind = $proof.source_file_set_kind; rust_file_count = [int]$proof.rust_file_count; definition_count = [int]$proof.definition_count; caller_count = [int]$proof.caller_count; definition = "$($proof.definitions[0].source_path):$($proof.definitions[0].source_line)"; status = $proof.status }
        inventory_summary_sha256 = Get-ObjectDigest $summary
        source_scan_sha256 = Get-ObjectDigest $scan
        canonical_write_proof_sha256 = Get-ObjectDigest $proof
        regression_fixtures_sha256 = Get-ObjectDigest $scan.regression_fixtures
        cutover_decision = 'PENDING_ROOT'
    }
}

function Get-ExpectedResultDocument($Inventory, [string]$InventoryFile) {
    if ($Inventory.PSObject.Properties.Name -contains 'source_revision') { Fail 'revision provenance is forbidden; use content-bound source evidence' }
    $inventoryPath = 'swarm/inventory/contour-cut.json'; $generatorRel = 'scripts/gen-contour-cut.ps1'; $verifierRel = 'scripts/verify-contour-cut.ps1'
    $authorityPath = 'swarm/decisions/W1-RESULT-ENVELOPE-PROGRAM-REVISION-v1.3.md'
    $inventoryHash = Get-Sha256 $InventoryFile; $generatorHash = Get-Sha256 (Join-Path $RepoRoot $generatorRel); $verifierHash = Get-Sha256 (Join-Path $RepoRoot $verifierRel)
    $mechanismHash = Get-Sha256 (Join-Path $RepoRoot $MechanismReviewPath); $authorityHash = Get-Sha256 (Join-Path $RepoRoot $authorityPath)
    $scan = $Inventory.source_scan; $summary = $Inventory.summary; $proof = $Inventory.canonical_write_proof
    $fixtures = @{}; foreach ($fixture in @($scan.regression_fixtures)) { $fixtures[[string]$fixture.id] = $fixture }
    foreach ($id in @('dynamic-command-program','dynamic-command-executable','suspended-job-spawn','suspended-job-spawn-with-limits','dynamic-governor-command','bootstrap-brief')) { if (-not $fixtures.ContainsKey($id)) { Fail "result regression fixture missing: $id" } }
    $findings = @(
        "The full-from-zero mechanism scans the deterministic union of $($scan.cached_rust_file_count) Git-cached and $($scan.nonignored_untracked_rust_file_count) non-ignored-untracked Rust files by direct file reads; it claims completeness only for the $(@($scan.grammar).Count) declared motifs over that current file set, never semantic/runtime exhaustiveness.",
        'Dynamic and qualified process constructors are emitted with exact local target resolution when available and UNKNOWN_PROCESS_TARGET otherwise. Windows suspended-job wrappers, process-executor symbols, Windows CreateProcess APIs, Tokio/Std/qualified constructors, and named-pipe client/server/transport/authentication operations are represented.',
        "Regression rows include $($fixtures['dynamic-command-program'].path):$($fixtures['dynamic-command-program'].line), $($fixtures['dynamic-command-executable'].path):$($fixtures['dynamic-command-executable'].line), $($fixtures['suspended-job-spawn'].path):$($fixtures['suspended-job-spawn'].line), $($fixtures['suspended-job-spawn-with-limits'].path):$($fixtures['suspended-job-spawn-with-limits'].line), $($fixtures['dynamic-governor-command'].path):$($fixtures['dynamic-governor-command'].line), and the cached $($fixtures['bootstrap-brief'].path) fixture.",
        'The bins/eliot/src/main.rs:604 legacy eliot-governor.exe coexistence check is negative_observation/non_join, not a launch/control join. Other legacy/process-state observations are likewise non-join evidence.',
        'schema_version remains schema_observation only; write_receipt/write_receipt_by_id remains unknown state-write evidence; GovernorConfig roles remain import/parse/type_reference and never imply runtime join.',
        "Exact §5.1 proof over the cached plus non-ignored-untracked Rust union is one commit_canonical definition at $($proof.definitions[0].source_path):$($proof.definitions[0].source_line) and zero callers; the independent verifier recomputes anchors and tamper-tests this proof.",
        'No cutover A, B, or C is selected; §5.2 decision authority remains Root.'
    )
    $verification = @(
        'pwsh -NoProfile -File scripts/gen-contour-cut.ps1 -SelfTest: PASS',
        "pwsh -NoProfile -File scripts/gen-contour-cut.ps1: PASS ($($summary.row_count) rows; $($scan.union_rust_file_count) Rust files)",
        'pwsh -NoProfile -File scripts/gen-contour-cut.ps1 -Check: PASS',
        'pwsh -NoProfile -File scripts/verify-contour-cut.ps1 -SelfTest: PASS (omitted edge, source-stage, source/result family envelope, duplicate, negative, and §5.1 tamper checks)',
        'pwsh -NoProfile -File scripts/verify-contour-cut.ps1: PASS (declared grammar, Cargo edges, source anchors/digests, §5.1 proof, and full result envelope independently recomputed)',
        'git diff --check -- scripts/gen-contour-cut.ps1 scripts/verify-contour-cut.ps1 swarm/inventory/contour-cut.json swarm/results/W1-05.json: PASS'
    )
    $limitations = @(
        'The source census is complete only for the declared grammar over the current cached plus non-ignored-untracked Rust union; it is not a semantic/runtime call graph.',
        'Dynamic targets and IPC endpoints remain UNKNOWN unless exact local evidence resolves them; package names, imports, wrappers, and symbols do not imply a runtime connection.',
        'Proof ceiling excludes runtime liveness, authenticated invocation traces, signed bundle validation, parity, Product Pulse, and cutover selection.',
        'Git category and concurrent-worktree observations are non-authoritative; this envelope binds current source bytes, explicit policy constants, and artifact hashes only.'
    )
    $mechanism = [ordered]@{ path = $MechanismReviewPath; sha256 = $mechanismHash; status = 'LINKED' }; $authority = [ordered]@{ path = $authorityPath; sha256 = $authorityHash }
    $structured = [ordered]@{
        schema_version = $ResultSchemaVersion; authority_status = 'EVIDENCE_ONLY'; work_item_id = 'W1-05'; disposition = 'EVIDENCE_ONLY'
        artifacts = [ordered]@{ inventory = [ordered]@{ path = $inventoryPath; sha256 = $inventoryHash }; generator = [ordered]@{ path = $generatorRel; sha256 = $generatorHash }; verifier = [ordered]@{ path = $verifierRel; sha256 = $verifierHash }; generator_sha256 = $generatorHash; verifier_sha256 = $verifierHash; inventory_sha256 = $inventoryHash }
        evidence = @('content-bound path plus byte source census','observational Git category fields','full-envelope and per-family tamper verification')
        discriminator_before = [ordered]@{ status = 'TEMPLATE_CONTROLLED_RESULT_REJECTED'; reason = 'Generic evidence fields were inherited from the previous result file' }
        discriminator_after = [ordered]@{ status = 'FULL_FROM_ZERO_RESULT'; content_bound = $true; categories_observational = $true }
        uncertainty = 'Static declared-grammar census only; no runtime liveness or cutover authority.'
        unresolved_questions = @('Runtime invocation and authenticated contour join remain unproven','Root cutover decision remains pending')
        proposed_effects = @('Preserve EVIDENCE_ONLY','Do not select cutover')
        evidence_lineage = [ordered]@{ program_authority = [ordered]@{ path = $authorityPath; sha256 = $authorityHash }; challenge = [ordered]@{ path = $MechanismReviewPath; sha256 = $mechanismHash }; inventory = [ordered]@{ path = $inventoryPath; sha256 = $inventoryHash } }
        observed_worktree_state = 'CONTENT_BOUND_SOURCE_UNION; GIT_CATEGORIES_OBSERVATIONAL_ONLY'
        mechanism_review = $mechanism; program_authority = $authority
        changed_files = @($generatorRel,$verifierRel,$inventoryPath,'swarm/results/W1-05.json',$MechanismReviewPath)
        result = Get-ExpectedResultProjection $Inventory
        findings = $findings; verification = $verification; limitations = $limitations
        external_routing_evidence = @('ses_fccf606fcffeCw3AOMDCG4YIiu','ses_fcc6cdf37ffeO3ylWsg4uFG2ct')
    }
    return [ordered]@{ schema_version = 'eliot.bootstrap-work-result.v1'; authority_status = 'EVIDENCE_ONLY'; work_item_id = 'W1-05'; structured_result = $structured }
}

function Assert-ResultProjection($Inventory, $Result, [string]$InventoryFile, $SourceSet, [string]$ResultFile = '') {
    if ($Result.schema_version -eq 'eliot.bootstrap-work-result.v1') { AssertExact $Result @('schema_version','authority_status','work_item_id','structured_result') 'result wrapper'; if ($Result.authority_status -cne 'EVIDENCE_ONLY') { Fail 'result wrapper authority mismatch' }; $Result = $Result.structured_result }
    $expectedStructured = (Get-ExpectedResultDocument $Inventory $InventoryFile).structured_result
    AssertExact $Result @('schema_version','authority_status','work_item_id','disposition','artifacts','evidence','discriminator_before','discriminator_after','uncertainty','unresolved_questions','proposed_effects','evidence_lineage','observed_worktree_state','mechanism_review','program_authority','changed_files','result','findings','verification','limitations','external_routing_evidence') 'structured result'
    if ($Result.schema_version -ne $ResultSchemaVersion -or $Result.authority_status -ne 'EVIDENCE_ONLY' -or $Result.work_item_id -ne 'W1-05') { Fail 'result envelope schema/authority mismatch' }
    if ($Result.PSObject.Properties.Name -contains 'source_revision' -or $Inventory.PSObject.Properties.Name -contains 'source_revision') { Fail 'revision provenance is forbidden; use content-bound source evidence' }
    if ($Result.mechanism_review.path -ne $MechanismReviewPath -or $Result.mechanism_review.status -ne 'LINKED' -or -not (Test-Path -LiteralPath (Join-Path $RepoRoot $MechanismReviewPath) -PathType Leaf) -or $Result.mechanism_review.sha256 -cne (Get-Sha256 (Join-Path $RepoRoot $MechanismReviewPath))) { Fail 'mechanism review link/digest drift' }
    $expectedChanged = @('scripts/gen-contour-cut.ps1','scripts/verify-contour-cut.ps1','swarm/inventory/contour-cut.json','swarm/results/W1-05.json','swarm/challenges/W1-05-MECHANISM-REVIEW.md'); if ((@($Result.changed_files | Sort-Object) -join '|') -cne (($expectedChanged | Sort-Object) -join '|')) { Fail 'result changed-files envelope drift' }
    $authorityPath='swarm/decisions/W1-RESULT-ENVELOPE-PROGRAM-REVISION-v1.3.md'; if ($Result.program_authority.path -cne $authorityPath -or $Result.program_authority.sha256 -cne (Get-Sha256 (Join-Path $RepoRoot $authorityPath))) { Fail 'program authority binding drift' }
    AssertExact $Result.artifacts @('inventory','generator','verifier','generator_sha256','verifier_sha256','inventory_sha256') 'result artifacts'; $generatorPath = Join-Path $RepoRoot 'scripts/gen-contour-cut.ps1'; $verifierPath = Join-Path $RepoRoot 'scripts/verify-contour-cut.ps1'; $expectedInventoryHash = Get-Sha256 $InventoryFile; $expectedGeneratorHash = Get-Sha256 $generatorPath; $expectedVerifierHash = Get-Sha256 $verifierPath; if ($Result.artifacts.inventory.path -cne 'swarm/inventory/contour-cut.json' -or $Result.artifacts.generator.path -cne 'scripts/gen-contour-cut.ps1' -or $Result.artifacts.verifier.path -cne 'scripts/verify-contour-cut.ps1' -or $Result.artifacts.generator.sha256 -cne $expectedGeneratorHash -or $Result.artifacts.verifier.sha256 -cne $expectedVerifierHash -or $Result.artifacts.inventory.sha256 -cne $expectedInventoryHash -or $Result.artifacts.generator_sha256 -cne $expectedGeneratorHash -or $Result.artifacts.verifier_sha256 -cne $expectedVerifierHash -or $Result.artifacts.inventory_sha256 -cne $expectedInventoryHash) { Fail 'result artifact hash envelope drift' }
    if ($Result.result.disposition -ne 'IMPLEMENTED' -or $Result.result.cutover_decision -ne 'PENDING_ROOT' -or $Inventory.cutover_decision.selected -ne $null) { Fail 'result selected cutover/disposition drift' }
    if ([string]$Result.observed_worktree_state -cne [string]$expectedStructured.observed_worktree_state) { Fail 'result observed-worktree-state drift' }
    if ((@($Result.result.contour_a) -join '|') -cne (@($Inventory.contours.A) -join '|') -or (@($Result.result.contour_b) -join '|') -cne (@($Inventory.contours.B) -join '|')) { Fail 'result contour projection drift' }
    if ((@($Result.findings) -join "`0") -cne (@($expectedStructured.findings) -join "`0")) { Fail 'result findings drift' }
    if ((@($Result.verification) -join "`0") -cne (@($expectedStructured.verification) -join "`0")) { Fail 'result verification drift' }
    if ((@($Result.limitations) -join "`0") -cne (@($expectedStructured.limitations) -join "`0")) { Fail 'result limitations drift' }
    if ((@($Result.external_routing_evidence) -join '|') -cne (@($expectedStructured.external_routing_evidence) -join '|')) { Fail 'result external-routing evidence drift' }
    $scanResult = $Result.result.source_scan; $scan = $Inventory.source_scan; if ($scanResult.file_set_kind -ne $scan.file_set_kind -or $scanResult.provenance -ne 'content_bound_path_plus_bytes' -or $scanResult.rust_files_sha256 -ne $scan.rust_files_sha256 -or $scanResult.grammar_file_set -ne $scan.grammar_file_set -or [int]$scanResult.cached_rust_file_count -ne [int]$scan.cached_rust_file_count -or [int]$scanResult.nonignored_untracked_rust_file_count -ne [int]$scan.nonignored_untracked_rust_file_count -or [int]$scanResult.union_rust_file_count -ne [int]$scan.union_rust_file_count -or [int]$scanResult.grammar_motifs -ne @($scan.grammar).Count -or [int]$scanResult.hit_count -ne [int]$scan.hit_count -or [int]$scanResult.row_count -ne [int]$scan.row_count) { Fail 'result source-scan envelope drift' }
    if ((Get-ObjectDigest $scanResult.motif_hit_counts) -ne (Get-ObjectDigest $scan.motif_hit_counts) -or (Get-ObjectDigest $scanResult.motif_row_counts) -ne (Get-ObjectDigest $scan.motif_row_counts)) { Fail 'result motif-count envelope drift' }
    if ([int]$Result.result.rows -ne [int]$Inventory.summary.row_count) { Fail 'result row-count envelope drift' }
    if ((Get-ObjectDigest $Result.result.edge_class_counts) -ne (Get-ObjectDigest $Inventory.summary.edge_class_counts) -or (Get-ObjectDigest $Result.result.status_counts) -ne (Get-ObjectDigest $Inventory.summary.status_counts)) { Fail 'result class/status envelope drift' }
    $semantic = $Result.result.semantic_counts; $summary = $Inventory.summary; foreach ($field in @('negative_observation_non_join','process_launch_observation','process_wrapper_observation','runtime_ipc_observation','launch_control_observation','schema_observation','state_write_unknown','unknown_process_target','unknown_ipc_target','unknown_launch_target')) { if ([int]$semantic.$field -ne [int]$summary.$field) { Fail "result semantic-count envelope drift: $field" } }; if ([int]$semantic.present -ne [int]$summary.status_counts.present -or [int]$semantic.absent -ne [int]$summary.status_counts.absent -or [int]$semantic.unknown -ne [int]$summary.status_counts.unknown) { Fail 'result status semantic envelope drift' }
    if ([int]$Result.result.cargo_direct_edges.A_TO_B.present -ne @($Inventory.rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'A_TO_B' -and $_.status -eq 'present' }).Count -or [int]$Result.result.cargo_direct_edges.A_TO_B.absent -ne @($Inventory.rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'A_TO_B' -and $_.status -eq 'absent' }).Count -or [int]$Result.result.cargo_direct_edges.B_TO_A.present -ne @($Inventory.rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'B_TO_A' -and $_.status -eq 'present' }).Count -or [int]$Result.result.cargo_direct_edges.B_TO_A.absent -ne @($Inventory.rows | Where-Object { $_.edge_class -eq 'cargo_dependency' -and $_.direction -eq 'B_TO_A' -and $_.status -eq 'absent' }).Count) { Fail 'result Cargo edge envelope drift' }
    if ([int]$Result.result.canonical_write_proof.rust_file_count -ne [int]$Inventory.canonical_write_proof.rust_file_count -or [int]$Result.result.canonical_write_proof.definition_count -ne [int]$Inventory.canonical_write_proof.definition_count -or [int]$Result.result.canonical_write_proof.caller_count -ne [int]$Inventory.canonical_write_proof.caller_count -or $Result.result.canonical_write_proof.status -ne $Inventory.canonical_write_proof.status -or $Result.result.canonical_write_proof.definition -ne "$($Inventory.canonical_write_proof.definitions[0].source_path):$($Inventory.canonical_write_proof.definitions[0].source_line)") { Fail 'result canonical-proof envelope drift' }
    if ($Result.result.inventory_summary_sha256 -ne (Get-ObjectDigest $Inventory.summary) -or $Result.result.source_scan_sha256 -ne (Get-ObjectDigest $Inventory.source_scan) -or $Result.result.canonical_write_proof_sha256 -ne (Get-ObjectDigest $Inventory.canonical_write_proof)) { Fail 'result digest envelope drift' }
    if ((Get-ObjectDigest $Result.result.regression_fixtures) -ne (Get-ObjectDigest $Inventory.source_scan.regression_fixtures) -or $Result.result.regression_fixtures_sha256 -ne (Get-ObjectDigest $Inventory.source_scan.regression_fixtures)) { Fail 'result regression fixture envelope drift' }
    if (-not [string]::IsNullOrWhiteSpace($ResultFile)) { Assert-CanonicalResultBytes $ResultFile (Get-Content -LiteralPath $ResultFile -Raw | ConvertFrom-Json) }
}

function Assert-ResultEnvelope($Inventory, $Result, [string]$InventoryFile, $SourceSet, [string]$ResultFile = '') {
    Assert-ResultProjection $Inventory $Result $InventoryFile $SourceSet
    $expectedBytes = Get-JsonBytes (Get-ExpectedResultDocument $Inventory $InventoryFile)
    $actualBytes = if ([string]::IsNullOrWhiteSpace($ResultFile)) { Get-JsonBytes $Result } else { [IO.File]::ReadAllBytes($ResultFile) }
    if (-not [Linq.Enumerable]::SequenceEqual[byte]([byte[]]$actualBytes, [byte[]]$expectedBytes)) { Fail 'result envelope raw bytes differ from independent full-from-zero expectation' }
}

function Get-ExpectedSummary($Rows, $Census, $SourceSet) {
    $edgeCounts = [ordered]@{}; foreach ($group in @($Rows | Group-Object edge_class | Sort-Object Name)) { $edgeCounts[$group.Name] = $group.Count }
    $statusCounts = [ordered]@{}; foreach ($group in @($Rows | Group-Object status | Sort-Object Name)) { $statusCounts[$group.Name] = $group.Count }
    $cargo = @($Rows | Where-Object edge_class -eq 'cargo_dependency')
    return [ordered]@{
        row_count = $Rows.Count; cargo_direct_present = @($cargo | Where-Object status -eq 'present').Count; cargo_direct_absent = @($cargo | Where-Object status -eq 'absent').Count
        source_row_count = $Census.RowCount; source_hit_count = $Census.HitCount; edge_class_counts = $edgeCounts; status_counts = $statusCounts
        negative_observation_non_join = @($Rows | Where-Object { $_.edge_class -eq 'negative_observation' -and $_.relation -eq 'non_join' }).Count
        process_launch_observation = @($Rows | Where-Object edge_class -eq 'process_launch_observation').Count; process_wrapper_observation = @($Rows | Where-Object edge_class -eq 'process_wrapper_observation').Count
        runtime_ipc_observation = @($Rows | Where-Object edge_class -eq 'runtime_ipc_observation').Count; launch_control_observation = @($Rows | Where-Object edge_class -eq 'launch_control_observation').Count
        schema_observation = @($Rows | Where-Object edge_class -eq 'schema_observation').Count; state_write_unknown = @($Rows | Where-Object { $_.edge_class -eq 'state_write_observation' -and $_.status -eq 'unknown' }).Count
        unknown_process_target = @($Rows | Where-Object to -eq $UnknownProcessTarget).Count; unknown_ipc_target = @($Rows | Where-Object to -eq $UnknownIpcTarget).Count; unknown_launch_target = @($Rows | Where-Object to -eq $UnknownLaunchTarget).Count
        cached_rust_file_count = $SourceSet.Cached.Count; nonignored_untracked_rust_file_count = $SourceSet.Untracked.Count; union_rust_file_count = $SourceSet.Union.Count
    }
}

function Assert-InventoryEnvelope($Inventory, $SourceSet, [hashtable]$Targets, $ExpectedCensus, [string]$InventoryFile) {
    AssertOrdered $Inventory @('schema_version','authority_status','work_item_id','cargo_metadata_sha256','mechanism_review','contours','cutover_decision','source_scan','rows','canonical_write_proof','summary','proof_ceiling','external_routing_evidence') 'inventory'
    AssertOrdered $Inventory.mechanism_review @('path','sha256','status') 'inventory mechanism review'
    if ($Inventory.mechanism_review.path -cne $MechanismReviewPath -or $Inventory.mechanism_review.status -cne 'LINKED' -or $Inventory.mechanism_review.sha256 -cne (Get-Sha256 (Join-Path $RepoRoot $MechanismReviewPath))) { Fail 'inventory mechanism review drift' }
    AssertOrdered $Inventory.contours @('A','B') 'inventory contours'
    if ((@($Inventory.contours.A) -join '|') -cne ($ContourA -join '|') -or (@($Inventory.contours.B) -join '|') -cne ($ContourB -join '|')) { Fail 'inventory contour definition drift' }
    AssertOrdered $Inventory.cutover_decision @('status','owner','selected','allowed_options') 'inventory cutover decision'
    if ($Inventory.cutover_decision.status -cne 'PENDING_ROOT' -or $Inventory.cutover_decision.owner -cne 'ROOT' -or $null -ne $Inventory.cutover_decision.selected -or (@($Inventory.cutover_decision.allowed_options) -join '|') -cne 'A|B|C') { Fail 'inventory cutover policy drift' }
    $scan = $Inventory.source_scan
    AssertOrdered $scan @('file_set_kind','provenance','cached_rust_file_count','nonignored_untracked_rust_file_count','union_rust_file_count','nonignored_untracked_rust_files','rust_files','rust_file_bindings','rust_files_sha256','grammar_file_set','grammar','motif_hit_counts','motif_row_counts','hit_count','row_count','completeness_statement','semantic_exhaustiveness_claim','target_map','regression_fixtures') 'source scan'
    foreach ($binding in @($scan.rust_file_bindings)) { AssertOrdered $binding @('path','sha256') 'source binding' }
    $grammar = @(Get-Grammar); if (@($scan.grammar).Count -ne $grammar.Count) { Fail 'source grammar count drift' }
    for ($index = 0; $index -lt $grammar.Count; $index++) { AssertOrdered $scan.grammar[$index] @('id','pattern','edge_class','resolver','kind','semantics') "source grammar[$index]"; foreach ($field in @('id','pattern','edge_class','resolver','kind','semantics')) { if ([string]$scan.grammar[$index].$field -cne [string]$grammar[$index].$field) { Fail "source grammar drift: $($grammar[$index].id).$field" } } }
    $motifIds = @($grammar | ForEach-Object id); AssertOrdered $scan.motif_hit_counts $motifIds 'motif hit counts'; AssertOrdered $scan.motif_row_counts $motifIds 'motif row counts'
    if ((Get-ObjectDigest $scan.motif_hit_counts) -cne (Get-ObjectDigest $ExpectedCensus.HitCounts) -or (Get-ObjectDigest $scan.motif_row_counts) -cne (Get-ObjectDigest $ExpectedCensus.RowCounts) -or [double]$scan.hit_count -ne [double]$ExpectedCensus.HitCount -or [int]$scan.row_count -ne [int]$ExpectedCensus.RowCount) { Fail 'source census aggregate drift' }
    $targetKeys = @($Targets.Keys | Sort-Object); AssertOrdered $scan.target_map $targetKeys 'source target map'; foreach ($key in $targetKeys) { if ([string]$scan.target_map.PSObject.Properties[$key].Value -cne [string]$Targets[$key]) { Fail "source target map drift: $key" } }
    foreach ($fixture in @($scan.regression_fixtures)) { AssertOrdered $fixture @('id','path','source_set','source_file_sha256','motif_id','line','target','source_match_text') 'regression fixture' }
    $rowFields = @('id','from','to','edge_class','relation','direction','motif_id','source_path','source_line','source_symbol','source_symbol_text','source_pattern','source_match_text','source_file_sha256','source_symbol_sha256','source_match_sha256','source_file_set','target_resolution','status','severity','join_claim','falsifier')
    foreach ($row in @($Inventory.rows)) { AssertOrdered $row $rowFields "inventory row $($row.id)" }
    AssertOrdered $Inventory.canonical_write_proof @('symbol','source_file_set_kind','rust_file_count','definition_pattern','reference_pattern','definition_count','caller_count','definitions','callers','status','falsifier') 'canonical write proof'
    $proofWitnessFields = @('source_path','source_line','source_symbol','source_symbol_text','source_match_text','source_file_sha256','source_symbol_sha256','source_match_sha256','source_file_set','package')
    foreach ($witness in @($Inventory.canonical_write_proof.definitions) + @($Inventory.canonical_write_proof.callers)) { AssertOrdered $witness $proofWitnessFields 'canonical write proof witness' }
    $expectedSummary = Get-ExpectedSummary @($Inventory.rows) $ExpectedCensus $SourceSet
    AssertOrdered $Inventory.summary @('row_count','cargo_direct_present','cargo_direct_absent','source_row_count','source_hit_count','edge_class_counts','status_counts','negative_observation_non_join','process_launch_observation','process_wrapper_observation','runtime_ipc_observation','launch_control_observation','schema_observation','state_write_unknown','unknown_process_target','unknown_ipc_target','unknown_launch_target','cached_rust_file_count','nonignored_untracked_rust_file_count','union_rust_file_count') 'inventory summary'
    AssertOrdered $Inventory.summary.edge_class_counts @($expectedSummary.edge_class_counts.Keys) 'inventory edge counts'; AssertOrdered $Inventory.summary.status_counts @($expectedSummary.status_counts.Keys) 'inventory status counts'
    if ((Get-ObjectDigest $Inventory.summary) -cne (Get-ObjectDigest $expectedSummary)) { Fail 'inventory summary drift' }
    $expectedCeiling = 'Complete current cached plus non-ignored-untracked Rust file-set census for the declared grammar plus Cargo metadata, content-bound by path and current bytes. This is not a semantic/runtime call graph and does not prove liveness, authenticated invocation, signed bundle, parity, or cutover.'
    if ([string]$Inventory.proof_ceiling -cne $expectedCeiling -or (@($Inventory.external_routing_evidence) -join '|') -cne 'ses_fccf606fcffeCw3AOMDCG4YIiu|ses_fcc6cdf37ffeO3ylWsg4uFG2ct') { Fail 'inventory proof ceiling/routing drift' }
    $canonicalBytes = Get-JsonBytes $Inventory; $actualBytes = [IO.File]::ReadAllBytes($InventoryFile)
    if (-not [Linq.Enumerable]::SequenceEqual[byte]([byte[]]$actualBytes, [byte[]]$canonicalBytes)) { Fail 'inventory raw bytes are not canonical UTF-8 JSON' }
}
function Assert-CanonicalResultBytes([string]$Path, $Result) { $expected=(($Result|ConvertTo-Json -Depth 100)+"`n"); if(([IO.File]::ReadAllText($Path)) -cne $expected){Fail 'result raw bytes are not canonical JSON'} }

function Invoke-SelfTest {
    if (Test-Path -LiteralPath $ResultPath -PathType Leaf) { Assert-CanonicalResultBytes $ResultPath (Get-Content -LiteralPath $ResultPath -Raw | ConvertFrom-Json) }
    if (-not (Test-Path -LiteralPath $InventoryPath -PathType Leaf) -or -not (Test-Path -LiteralPath $ResultPath -PathType Leaf)) { Fail 'inventory/result missing' }
    $ownedPaths=@($InventoryPath,$ResultPath,(Join-Path $RepoRoot 'scripts/gen-contour-cut.ps1'),(Join-Path $RepoRoot 'scripts/verify-contour-cut.ps1'))
    $ownedBytesBefore=@{};$ownedStampsBefore=@{};foreach($ownedPath in $ownedPaths){$ownedFull=[IO.Path]::GetFullPath($ownedPath);$ownedBytesBefore[$ownedFull]=[IO.File]::ReadAllBytes($ownedFull);$ownedStampsBefore[$ownedFull]=(Get-Item -LiteralPath $ownedFull).LastWriteTimeUtc.Ticks}
    $customInventory=[IO.Path]::GetTempFileName();$customResult=[IO.Path]::GetTempFileName()
    Assert-GeneratorCliRejected @('-InventoryOnly') '-InventoryOnly requires explicit -OutputPath'
    try {
        foreach($ownedPath in $ownedPaths){Assert-GeneratorCliRejected @('-Check','-InventoryOnly','-OutputPath',$ownedPath) '-InventoryOnly output must not target a generator-owned path'}
        Assert-GeneratorCliRejected @('-Check','-InventoryOnly','-OutputPath',($customInventory+':w1-selftest')) '-InventoryOnly output must not use an alternate data stream or control colon'
        Assert-GeneratorCliRejected @('-Check','-InventoryOnly','-OutputPath',(Join-Path (Split-Path $customInventory -Parent) 'W1SAFE~1.tmp')) '-InventoryOnly output must not use a Win32-normalized path alias'
        Assert-GeneratorCliRejected @('-Check','-InventoryOnly','-OutputPath',('\\localhost\'+$RepoRoot.Substring(0,1)+'$'+$RepoRoot.Substring(2)+'\swarm\inventory\contour-cut.json')) '-InventoryOnly output must not use a UNC or device path'
        Assert-GeneratorCliRejected @('-Check','-InventoryOnly','-OutputPath',(Join-Path $RepoRoot 'Cargo.toml')) '-InventoryOnly output must stay under the process temporary directory'
        Assert-GeneratorCliRejected @('-OutputPath',$customInventory,'-ResultPath',$customResult) 'custom output paths require explicit -InventoryOnly'
        Assert-GeneratorCliRejected @('-InventoryOnly','-ResultPath',$customResult) '-InventoryOnly cannot combine with -ResultPath'
        Assert-VerifierCliRejected '' '-ResultPath must be non-empty when supplied'
        Assert-VerifierCliRejected '   ' '-ResultPath must be non-empty when supplied'
    } finally { Remove-Item -LiteralPath $customInventory,$customResult -Force -ErrorAction SilentlyContinue }
    foreach($ownedPath in $ownedPaths){$ownedFull=[IO.Path]::GetFullPath($ownedPath);if(-not [Linq.Enumerable]::SequenceEqual([byte[]]$ownedBytesBefore[$ownedFull],[byte[]][IO.File]::ReadAllBytes($ownedFull)) -or (Get-Item -LiteralPath $ownedFull).LastWriteTimeUtc.Ticks -ne $ownedStampsBefore[$ownedFull]){Fail 'rejected CLI calls mutated a contour generator-owned path'}}
    $inventory = Get-Content -LiteralPath $InventoryPath -Raw | ConvertFrom-Json; $result = Get-Content -LiteralPath $ResultPath -Raw | ConvertFrom-Json; Assert-Basic $inventory; $sourceSet = Get-RustSourceSet; Assert-SourceSet $inventory $sourceSet; Assert-SourceEvidence $inventory $sourceSet; Assert-RegressionFixtures $inventory $sourceSet; $metadata = Get-CargoMetadata; $roots = Get-PackageRoots @($metadata.Json.packages | Sort-Object name); $targets = Get-TargetMap @($metadata.Json.packages | Sort-Object name); $expected = Get-ExpectedCensus $sourceSet $roots $targets; $proof = Get-ExpectedProof $sourceSet $roots; Assert-InventoryEnvelope $inventory $sourceSet $targets $expected $InventoryPath; Assert-ResultEnvelope $inventory $result $InventoryPath $sourceSet $ResultPath
    $fixtureRoot = Join-Path ([IO.Path]::GetTempPath()) ('eliot-w1-05-verifier-fixture-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory -Path (Join-Path $fixtureRoot 'cached') -Force | Out-Null; New-Item -ItemType Directory -Path (Join-Path $fixtureRoot 'untracked') -Force | Out-Null
    try { $cachedPath = Join-Path $fixtureRoot 'cached/cached.rs'; $untrackedPath = Join-Path $fixtureRoot 'untracked/untracked.rs'; [IO.File]::WriteAllText($cachedPath, 'fn cached_fixture() {}' + "`n", [Text.UTF8Encoding]::new($false)); [IO.File]::WriteAllText($untrackedPath, 'fn untracked_fixture() {}' + "`n", [Text.UTF8Encoding]::new($false)); $synthetic = New-RustSourceSet @('cached/cached.rs') @('untracked/untracked.rs') $fixtureRoot; if ($synthetic.Cached.Count -ne 1 -or $synthetic.Untracked.Count -ne 1 -or $synthetic.Union.Count -ne 2 -or $synthetic.Kind['untracked/untracked.rs'] -cne 'nonignored_untracked') { throw 'verifier synthetic source-set classification/count drift' }; $before = @($synthetic.Bindings | Where-Object path -eq 'untracked/untracked.rs')[0].sha256; $moved = New-RustSourceSet @('cached/cached.rs','untracked/untracked.rs') @() $fixtureRoot; if ($moved.Cached.Count -ne 2 -or $moved.Untracked.Count -ne 0 -or $moved.Union.Count -ne 2 -or $moved.Kind['untracked/untracked.rs'] -cne 'cached' -or @($moved.Bindings | Where-Object path -eq 'untracked/untracked.rs')[0].sha256 -cne $before) { throw 'verifier synthetic source-set stage transition drift' }; [IO.File]::WriteAllText($untrackedPath, 'fn untracked_fixture_tampered() {}' + "`n", [Text.UTF8Encoding]::new($false)); $tampered = New-RustSourceSet @('cached/cached.rs') @('untracked/untracked.rs') $fixtureRoot; if (@($tampered.Bindings | Where-Object path -eq 'untracked/untracked.rs')[0].sha256 -ceq $before) { throw 'verifier synthetic content tamper accepted' }; try { New-RustSourceSet @('cached/missing.rs') @() $fixtureRoot; throw 'verifier synthetic missing path accepted' } catch { if ($_.Exception.Message -notmatch 'missing') { throw } } } finally { Remove-Item -LiteralPath $fixtureRoot -Recurse -Force -ErrorAction SilentlyContinue }
    $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $drop = @($copy.rows | Where-Object id -like 'CENSUS-*')[0].id; $copy.rows = @($copy.rows | Where-Object id -ne $drop); try { Assert-ExactRows @($copy.rows | Where-Object id -like 'CENSUS-*') $expected.Rows 'census'; throw 'omitted discoverable edge accepted' } catch { if ($_.Exception.Message -notmatch 'omitted/discoverable') { throw } }
    $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $negative = @($copy.rows | Where-Object edge_class -eq 'negative_observation')[0]; $negative.edge_class = 'launch_control'; $copy.rows = @($copy.rows | Sort-Object edge_class,direction,from,to,id); try { Assert-Basic $copy; throw 'negative tamper accepted' } catch { if ($_.Exception.Message -notmatch 'negative') { throw } }
    $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.source_scan.nonignored_untracked_rust_file_count = 1; try { Assert-SourceSet $copy $sourceSet; throw 'source-stage count tamper accepted' } catch { if ($_.Exception.Message -notmatch 'source-set|untracked|count') { throw } }
    $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $anchor = @($copy.rows | Where-Object { $_.motif_id -ne 'cargo-metadata' })[0]; $anchor.source_file_set = 'nonignored_untracked'; try { Assert-SourceEvidence $copy $sourceSet; throw 'source-stage row tamper accepted' } catch { if ($_.Exception.Message -notmatch 'stage|source-file-set|digest') { throw } }
    $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $anchor = @($copy.rows | Where-Object id -like 'CENSUS-*')[0]; $anchor.source_match_sha256 = '0' * 64; try { Assert-SourceEvidence $copy $sourceSet; throw 'source digest tamper accepted' } catch { if ($_.Exception.Message -notmatch 'digest') { throw } }
    foreach ($family in @('cargo_dependency','shared_contract_type','process_launch_observation','process_wrapper_observation','runtime_ipc_observation','launch_control_observation','schema_observation','state_write_observation','canonical_write_observation')) { $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $familyRows=@($copy.rows|Where-Object edge_class -eq $family); if ($familyRows.Count -gt 0) { $familyRow=$familyRows[0]; $familyRow.source_file_sha256='0'*64; try { Assert-SourceEvidence $copy $sourceSet; throw "per-family tamper accepted: $family" } catch { if ($_.Exception.Message -notmatch 'digest') { throw } } } }
    foreach ($kind in @('top-add','top-remove','row-add','summary-tamper','target-map-tamper')) {
        $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json
        switch ($kind) {
            'top-add' { $copy | Add-Member -NotePropertyName extra -NotePropertyValue tampered }
            'top-remove' { $null = $copy.PSObject.Properties.Remove('proof_ceiling') }
            'row-add' { $copy.rows[0] | Add-Member -NotePropertyName extra -NotePropertyValue tampered }
            'summary-tamper' { $copy.summary.row_count = [int]$copy.summary.row_count + 1 }
            'target-map-tamper' { $firstTarget = @($copy.source_scan.target_map.PSObject.Properties.Name)[0]; $copy.source_scan.target_map.PSObject.Properties[$firstTarget].Value = 'tampered' }
        }
        try { Assert-InventoryEnvelope $copy $sourceSet $targets $expected $InventoryPath; throw "inventory envelope tamper accepted: $kind" }
        catch { if ($_.Exception.Message -notmatch 'field order differs|summary drift|target map drift|raw bytes') { throw } }
    }
    foreach ($family in @('observed_worktree_state','findings','verification','limitations','external_routing_evidence')) { $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; if ($family -eq 'observed_worktree_state') { $copy.structured_result.$family = 'tampered' } elseif ($family -eq 'external_routing_evidence') { $copy.structured_result.$family = @('tampered') } else { $copy.structured_result.$family = @('tampered') }; try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw "result family tamper accepted: $family" } catch { if ($_.Exception.Message -notmatch 'result (observed-worktree-state|findings|verification|limitations|external-routing).*drift') { throw } } }
    foreach ($family in @('evidence','discriminator_before','discriminator_after','uncertainty','unresolved_questions','proposed_effects','evidence_lineage','disposition')) {
        $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json
        switch ($family) {
            'evidence' { $copy.structured_result.evidence = @('tampered') }
            'discriminator_before' { $copy.structured_result.discriminator_before.status = 'tampered' }
            'discriminator_after' { $copy.structured_result.discriminator_after.status = 'tampered' }
            'uncertainty' { $copy.structured_result.uncertainty = 'tampered' }
            'unresolved_questions' { $copy.structured_result.unresolved_questions = @('tampered') }
            'proposed_effects' { $copy.structured_result.proposed_effects = @('tampered') }
            'evidence_lineage' { $copy.structured_result.evidence_lineage.challenge.sha256 = '0' * 64 }
            'disposition' { $copy.structured_result.disposition = 'tampered' }
        }
        try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw "generic result tamper accepted: $family" }
        catch { if ($_.Exception.Message -notmatch 'raw bytes differ|schema/authority|selected cutover/disposition') { throw } }
    }
    foreach ($family in @('contour_a','contour_b')) { $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.structured_result.result.$family = @('tampered'); try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw "result contour tamper accepted: $family" } catch { if ($_.Exception.Message -notmatch 'contour projection') { throw } } }
    $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.structured_result.result.source_scan.cached_rust_file_count = 545; try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw 'result source-scan stage tamper accepted' } catch { if ($_.Exception.Message -notmatch 'source-scan') { throw } }
    $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.structured_result.result.rows = [int]$copy.structured_result.result.rows + 1; try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw 'result row-count tamper accepted' } catch { if ($_.Exception.Message -notmatch 'row-count') { throw } }
    foreach ($artifact in @('inventory','generator','verifier')) { $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.structured_result.artifacts.$artifact.sha256 = '0' * 64; try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw "nested artifact hash tamper accepted: $artifact" } catch { if ($_.Exception.Message -notmatch 'artifact hash') { throw } } }
    $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.structured_result.artifacts.verifier_sha256 = '0' * 64; try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw 'result hash tamper accepted' } catch { if ($_.Exception.Message -notmatch 'hash') { throw } }
    $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.structured_result.changed_files = @('tampered'); try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw 'result changed-files tamper accepted' } catch { if ($_.Exception.Message -notmatch 'changed-files') { throw } }
    $copy = $result | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.structured_result | Add-Member -NotePropertyName source_revision -NotePropertyValue 'tampered'; try { Assert-ResultEnvelope $inventory $copy $InventoryPath $sourceSet; throw 'result revision tamper accepted' } catch { if ($_.Exception.Message -notmatch 'revision|fields differ') { throw } }
    $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.canonical_write_proof.caller_count = 1; try { Assert-CanonicalProof $copy $proof; throw 'commit caller tamper accepted' } catch { if ($_.Exception.Message -notmatch 'commit_canonical|§5.1') { throw } }
    $copy = $inventory | ConvertTo-Json -Depth 100 | ConvertFrom-Json; $copy.rows = @($copy.rows + $copy.rows[0]); try { Assert-Basic $copy; throw 'duplicate tamper accepted' } catch { if ($_.Exception.Message -notmatch 'duplicated') { throw } }
    Write-Output "SELFTEST PASS: omitted edge, source-stage, dynamic/untracked union, source digest, result families, result envelope, duplicate, negative, and §5.1 tamper checks ($($inventory.summary.row_count) rows)"
}

if ($PSBoundParameters.ContainsKey('ResultPath') -and [string]::IsNullOrWhiteSpace($ResultPath)) { Fail '-ResultPath must be non-empty when supplied' }
if ($SelfTest) { Invoke-SelfTest; exit 0 }
if (-not (Test-Path -LiteralPath $InventoryPath -PathType Leaf) -or -not (Test-Path -LiteralPath $ResultPath -PathType Leaf)) { Fail 'inventory/result missing' }
$inventory = Get-Content -LiteralPath $InventoryPath -Raw | ConvertFrom-Json; $result = Get-Content -LiteralPath $ResultPath -Raw | ConvertFrom-Json; Assert-Basic $inventory; $sourceSet = Get-RustSourceSet; Assert-SourceSet $inventory $sourceSet; Assert-SourceEvidence $inventory $sourceSet; Assert-RegressionFixtures $inventory $sourceSet; $metadata = Get-CargoMetadata; $packages = @($metadata.Json.packages | Sort-Object name); $roots = Get-PackageRoots $packages; $targets = Get-TargetMap $packages; Assert-CargoRows $inventory $metadata; $expected = Get-ExpectedCensus $sourceSet $roots $targets; Assert-ExactRows @($inventory.rows | Where-Object id -like 'CENSUS-*') $expected.Rows 'census'; $proof = Get-ExpectedProof $sourceSet $roots; Assert-CanonicalProof $inventory $proof; Assert-InventoryEnvelope $inventory $sourceSet $targets $expected $InventoryPath; Assert-ResultEnvelope $inventory $result $InventoryPath $sourceSet $ResultPath; Write-Output "VERIFY PASS: $InventoryPath ($($inventory.summary.row_count) rows; $($sourceSet.Union.Count) cached+nonignored-untracked Rust files; declared grammar, Cargo edges, §5.1 proof, and result envelope independently recomputed)"
