[CmdletBinding()]
param(
    [switch] $List
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProfileVersion = 'eliot-w1-inventory-gate-v1'

function Fail([string] $Message) {
    throw "W1_VERIFY_FAIL: $Message"
}

function Invoke-NativeStep(
    [string] $StepId,
    [string] $FilePath,
    [string[]] $Arguments
) {
    Write-Output "W1_VERIFY_STEP_START id=$StepId"
    & $FilePath @Arguments
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        Fail "step=$StepId exit=$exitCode"
    }
    Write-Output "W1_VERIFY_STEP_PASS id=$StepId"
}

function Assert-SameFile(
    [string] $StepId,
    [string] $ExpectedPath,
    [string] $ActualPath
) {
    $expected = [IO.File]::ReadAllBytes($ExpectedPath)
    $actual = [IO.File]::ReadAllBytes($ActualPath)
    $expectedHash = [Convert]::ToHexString(
        [Security.Cryptography.SHA256]::HashData($expected)
    ).ToLowerInvariant()
    $actualHash = [Convert]::ToHexString(
        [Security.Cryptography.SHA256]::HashData($actual)
    ).ToLowerInvariant()
    if ($expected.Length -ne $actual.Length -or $expectedHash -cne $actualHash) {
        Fail "step=$StepId generated bytes differ: expected=$expectedHash actual=$actualHash"
    }
}

$tempRoot = $null
$exitCode = 0
try {
    $repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
    $pwsh = (Get-Command pwsh -ErrorAction Stop).Source
    $paths = [ordered]@{
        GenModules = Join-Path $repoRoot 'scripts/gen-module-manifests.ps1'
        VerifyModules = Join-Path $repoRoot 'scripts/verify-module-manifests.ps1'
        GenRefusals = Join-Path $repoRoot 'scripts/gen-refusals.ps1'
        VerifyRefusals = Join-Path $repoRoot 'scripts/verify-refusals.ps1'
        VerifyAcceptance = Join-Path $repoRoot 'scripts/verify-acceptance-cycle.ps1'
        GenConformance = Join-Path $repoRoot 'scripts/gen-conformance.ps1'
        VerifyConformance = Join-Path $repoRoot 'scripts/verify-conformance.ps1'
        GenContour = Join-Path $repoRoot 'scripts/gen-contour-cut.ps1'
        VerifyContour = Join-Path $repoRoot 'scripts/verify-contour-cut.ps1'
        GenPremises = Join-Path $repoRoot 'scripts/gen-w1-06-premises.ps1'
        VerifyPremises = Join-Path $repoRoot 'scripts/verify-w1-06-premises.ps1'
        GenComposition = Join-Path $repoRoot 'scripts/gen-composition-roots.ps1'
        VerifyComposition = Join-Path $repoRoot 'scripts/verify-composition-roots.ps1'
        ModulesInventory = Join-Path $repoRoot 'swarm/inventory/modules.json'
        PremisesInventory = Join-Path $repoRoot 'swarm/inventory/w1-06-premises.json'
    }
    foreach ($entry in $paths.GetEnumerator()) {
        if (-not (Test-Path -LiteralPath $entry.Value -PathType Leaf)) {
            Fail "required file is missing: $($entry.Value)"
        }
    }

    $steps = @(
        [pscustomobject]@{ Id = 'modules-generated-bytes'; Description = 'fresh W1-01 generation is byte-identical to modules.json' },
        [pscustomobject]@{ Id = 'modules-envelope-check'; Description = 'W1-01 generator owns an exact inventory plus evidence envelope pair' },
        [pscustomobject]@{ Id = 'modules-selftest'; Description = 'W1-01 independent verifier mutation fixtures' },
        [pscustomobject]@{ Id = 'refusals-selftest'; Description = 'W1-02 independent verifier mutation fixtures' },
        [pscustomobject]@{ Id = 'conformance-generator-selftest'; Description = 'W1-04 generator mutation fixtures' },
        [pscustomobject]@{ Id = 'conformance-verifier-selftest'; Description = 'W1-04 independent oracle mutation fixtures' },
        [pscustomobject]@{ Id = 'contour-generator-selftest'; Description = 'W1-05 generator mutation fixtures' },
        [pscustomobject]@{ Id = 'contour-verifier-selftest'; Description = 'W1-05 independent oracle mutation fixtures' },
        [pscustomobject]@{ Id = 'premises-generated-bytes'; Description = 'fresh W1-06 generation is byte-identical to premises inventory' },
        [pscustomobject]@{ Id = 'premises-envelope-check'; Description = 'W1-06 generator owns an exact inventory plus evidence envelope pair' },
        [pscustomobject]@{ Id = 'premises-verifier-selftest'; Description = 'W1-06 independent oracle mutation fixtures' },
        [pscustomobject]@{ Id = 'composition-verifier-selftest'; Description = 'W1-07 independent oracle mutation fixtures' },
        [pscustomobject]@{ Id = 'acceptance-cycle-selftest'; Description = 'W1-03 repository binding and digest mutation fixtures' },
        [pscustomobject]@{ Id = 'refusals-check'; Description = 'W1-02 canonical artifacts equal deterministic regeneration' },
        [pscustomobject]@{ Id = 'conformance-check'; Description = 'W1-04 canonical artifact equals deterministic regeneration' },
        [pscustomobject]@{ Id = 'contour-check'; Description = 'W1-05 canonical artifact equals deterministic regeneration' },
        [pscustomobject]@{ Id = 'composition-check'; Description = 'W1-07 canonical artifacts equal deterministic regeneration' },
        [pscustomobject]@{ Id = 'modules-oracle'; Description = 'W1-01 source-to-inventory independent oracle' },
        [pscustomobject]@{ Id = 'refusals-oracle'; Description = 'W1-02 source-to-inventory independent oracle' },
        [pscustomobject]@{ Id = 'acceptance-cycle-oracle'; Description = 'W1-03 seven-cell SCC and cut oracle' },
        [pscustomobject]@{ Id = 'conformance-oracle'; Description = 'W1-04 canonical-pair-to-matrix independent oracle' },
        [pscustomobject]@{ Id = 'contour-oracle'; Description = 'W1-05 whole-workspace contour independent oracle' },
        [pscustomobject]@{ Id = 'premises-oracle'; Description = 'W1-06 revised-premises independent oracle' },
        [pscustomobject]@{ Id = 'composition-oracle'; Description = 'W1-07 binary-root independent oracle' }
    )

    if ($List) {
        Write-Output "ELIOT_W1_VERIFY_PROFILE=$ProfileVersion"
        for ($index = 0; $index -lt $steps.Count; $index++) {
            Write-Output ('{0:D2} {1} | {2}' -f ($index + 1), $steps[$index].Id, $steps[$index].Description)
        }
        exit 0
    }

    $tempRoot = Join-Path ([IO.Path]::GetTempPath()) ("eliot-w1-verify-{0}" -f [guid]::NewGuid().ToString('N'))
    [void] (New-Item -ItemType Directory -Path $tempRoot)
    $tempModules = Join-Path $tempRoot 'modules.json'
    $tempPremises = Join-Path $tempRoot 'w1-06-premises.json'

    Write-Output "ELIOT_W1_VERIFY_PROFILE=$ProfileVersion"
    Write-Output "W1_VERIFY_ROOT=$repoRoot"

    Invoke-NativeStep 'modules-generated-bytes' $pwsh @('-NoProfile', '-File', $paths.GenModules, '-OutputPath', $tempModules, '-InventoryOnly')
    Assert-SameFile 'modules-generated-bytes' $paths.ModulesInventory $tempModules
    Invoke-NativeStep 'modules-envelope-check' $pwsh @('-NoProfile', '-File', $paths.GenModules, '-Check')
    Invoke-NativeStep 'modules-selftest' $pwsh @('-NoProfile', '-File', $paths.VerifyModules, '-SelfTest')
    Invoke-NativeStep 'refusals-selftest' $pwsh @('-NoProfile', '-File', $paths.VerifyRefusals, '-SelfTest')
    Invoke-NativeStep 'conformance-generator-selftest' $pwsh @('-NoProfile', '-File', $paths.GenConformance, '-SelfTest')
    Invoke-NativeStep 'conformance-verifier-selftest' $pwsh @('-NoProfile', '-File', $paths.VerifyConformance, '-SelfTest')
    Invoke-NativeStep 'contour-generator-selftest' $pwsh @('-NoProfile', '-File', $paths.GenContour, '-SelfTest')
    Invoke-NativeStep 'contour-verifier-selftest' $pwsh @('-NoProfile', '-File', $paths.VerifyContour, '-SelfTest')
    Invoke-NativeStep 'premises-generated-bytes' $pwsh @('-NoProfile', '-File', $paths.GenPremises, '-OutputPath', $tempPremises, '-InventoryOnly')
    Assert-SameFile 'premises-generated-bytes' $paths.PremisesInventory $tempPremises
    Invoke-NativeStep 'premises-envelope-check' $pwsh @('-NoProfile', '-File', $paths.GenPremises, '-Check')
    Invoke-NativeStep 'premises-verifier-selftest' $pwsh @('-NoProfile', '-File', $paths.VerifyPremises, '-SelfTest')
    Invoke-NativeStep 'composition-verifier-selftest' $pwsh @('-NoProfile', '-File', $paths.VerifyComposition, '-SelfTest')
    Invoke-NativeStep 'acceptance-cycle-selftest' $pwsh @('-NoProfile', '-File', $paths.VerifyAcceptance, '-SelfTest')

    Invoke-NativeStep 'refusals-check' $pwsh @('-NoProfile', '-File', $paths.GenRefusals, '-Check')
    Invoke-NativeStep 'conformance-check' $pwsh @('-NoProfile', '-File', $paths.GenConformance, '-Check')
    Invoke-NativeStep 'contour-check' $pwsh @('-NoProfile', '-File', $paths.GenContour, '-Check')
    Invoke-NativeStep 'composition-check' $pwsh @('-NoProfile', '-File', $paths.GenComposition, '-Check')

    Invoke-NativeStep 'modules-oracle' $pwsh @('-NoProfile', '-File', $paths.VerifyModules)
    Invoke-NativeStep 'refusals-oracle' $pwsh @('-NoProfile', '-File', $paths.VerifyRefusals)
    Invoke-NativeStep 'acceptance-cycle-oracle' $pwsh @('-NoProfile', '-File', $paths.VerifyAcceptance)
    Invoke-NativeStep 'conformance-oracle' $pwsh @('-NoProfile', '-File', $paths.VerifyConformance)
    Invoke-NativeStep 'contour-oracle' $pwsh @('-NoProfile', '-File', $paths.VerifyContour)
    Invoke-NativeStep 'premises-oracle' $pwsh @('-NoProfile', '-File', $paths.VerifyPremises)
    Invoke-NativeStep 'composition-oracle' $pwsh @('-NoProfile', '-File', $paths.VerifyComposition)

    Write-Output 'W1_VERIFY_RESULT=PASS'
}
catch {
    Write-Error $_.Exception.Message
    $exitCode = 1
}
finally {
    if ($null -ne $tempRoot -and (Test-Path -LiteralPath $tempRoot)) {
        Remove-Item -LiteralPath $tempRoot -Recurse -Force
    }
}
exit $exitCode
