[CmdletBinding()]
param([switch]$SelfTest)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$RepoRoot=Split-Path -Parent $PSScriptRoot
$ArchitecturePath=Join-Path $RepoRoot 'docs\normative\ELIOT_ARCHITECTURE.md'
$ImplementationPath=Join-Path $RepoRoot 'docs\normative\ELIOT_IMPLEMENTATION.md'
$DecisionPath=Join-Path $RepoRoot 'swarm\challenges\W1-RESULT-ENVELOPE-CONTRACT.md'
$GeneratorPath=Join-Path $RepoRoot 'scripts\gen-conformance.ps1'
$VerifierPath=Join-Path $RepoRoot 'scripts\verify-conformance.ps1'
$ConformancePath=Join-Path $RepoRoot 'docs\conformance.toml'
$ResultPath=Join-Path $RepoRoot 'swarm\results\W1-04.json'
$SupportingResultPath=Join-Path $RepoRoot 'swarm\results\W1-04-implementation.json'
function Rel([string]$p){([IO.Path]::GetRelativePath($RepoRoot,$p)).Replace('\','/')}
function Sha([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToUpperInvariant()}
function TextSha([string]$s){$h=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($s)))).Replace('-','').ToUpperInvariant()}finally{$h.Dispose()}}
function Norm([string]$v){if($null -eq $v){return ''};([regex]::Replace($v.Trim(),'[\t\r\n ]+',' '))}
function Toml([string]$v){$s=if($null -eq $v){''}else{[string]$v};'"'+$s.Replace('\','\\').Replace('"','\"').Replace("`r",'\r').Replace("`n",'\n').Replace("`t",'\t')+'"'}
function TomlArray($v){if($null -eq $v -or @($v).Count -eq 0){return '[]'};'['+((@($v)|%{Toml ([string]$_ )})-join ', ')+']'}
function Rows([string]$t,[string]$start,[string]$end,[string]$header,[string]$kind){$inside=$false;$fenced=$false;$head=$false;$sep=$false;$o=[Collections.Generic.List[object]]::new();foreach($line in($t -split "`r?`n")){if($line -match '^\s*```'){$fenced=-not$fenced;continue};if($fenced){continue};if(-not$inside){if($line -match $start){$inside=$true};continue};if($line -match $end){break};if(-not$head){if([string]::IsNullOrWhiteSpace($line)){continue};if($line -notmatch $header){continue};$head=$true;continue};if(-not$sep){if($line -match '^\|\s*:?-{3,}:?\s*\|\s*:?-{3,}:?\s*\|\s*:?-{3,}:?\s*\|\s*$'){$sep=$true;continue};if(-not[string]::IsNullOrWhiteSpace($line)){throw "$kind table separator is malformed"};continue};if([string]::IsNullOrWhiteSpace($line)){continue};if($kind -eq 'architecture' -and $line -match '^\|\s*`(ARCH-[A-Z]+-[0-9]+)`\s*\|\s*(Invariant|Contract)\s*\|\s*(.*?)\s*\|\s*$'){$o.Add([pscustomobject]@{Id=$Matches[1];Class=$Matches[2];Decision=$Matches[3].Trim()});continue};if($kind -eq 'implementation' -and $line -match '^\|\s*`(ARCH-[A-Z]+-[0-9]+)`\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$'){$o.Add([pscustomobject]@{Id=$Matches[1];ScopeOwner=$Matches[2].Trim();Proof=$Matches[3].Trim()});continue};if($line -match '^\|'){throw "$kind table contains an invalid row: $line"}};if(-not$inside -or -not$head -or -not$sep){throw "$kind table headings/header were not found"};$o.ToArray()}
function AssertPair($a,$i){if(@($a).Count -ne 58 -or @($i).Count -ne 58){throw 'A16.1/Appendix H must each contain exactly 58 rows'};$ai=@($a|% Id);$ii=@($i|% Id);if(@($ai|sort -Unique).Count -ne 58 -or @($ii|sort -Unique).Count -ne 58){throw 'duplicate anchor IDs'};$missing=@($ai|?{$_ -notin$ii});$extra=@($ii|?{$_ -notin$ai});if($missing.Count -or $extra.Count){throw "anchor sets differ: missing=$($missing -join ',') extra=$($extra -join ',')"}}
function Scope([string]$v){$s=Norm $v;$owner='UNKNOWN';$h=$s;if($s -match '^(.*?);\s*([^;]+)$'){$h=$Matches[1].Trim();$owner=$Matches[2].Trim()};[pscustomobject]@{Owner=$owner.Trim('`');Handles=@($h -split '\s*,\s*'|%{$_.Trim().Trim('`')}|?{$_})}}
function Model{$a=Rows (Get-Content -LiteralPath $ArchitecturePath -Raw) '^## A16\.1\. Decision anchors\s*$' '^## A16\.2\.' '^\|\s*ID\s*\|\s*Класс\s*\|\s*Решение\s*\|\s*$' architecture;$i=Rows (Get-Content -LiteralPath $ImplementationPath -Raw) '^# Appendix H\. Full Architecture conformance map\s*$' '^# Appendix I\.' '^\|\s*Architecture ID\s*\|\s*Primary implementation sections / owner\s*\|\s*Observable proof family\s*\|\s*$' implementation;AssertPair $a $i;$by=@{};$i|%{$by[$_.Id]=$_};$an=(($a|%{"$($_.Id)|$($_.Class)|$(Norm $_.Decision)"})-join "`n")+"`n";$inn=(($a|%{$r=$by[$_.Id];"$($_.Id)|$(Norm $r.ScopeOwner)|$(Norm $r.Proof)"})-join "`n")+"`n";[pscustomobject]@{A=$a;By=$by;AH=(Sha $ArchitecturePath);IH=(Sha $ImplementationPath);PH=(TextSha($an+"---`n"+$inn));GH=(Sha $GeneratorPath);VH=(Sha $VerifierPath);DH=(Sha $DecisionPath)}}
function Conformance($m){$l=[Collections.Generic.List[string]]::new();$l.Add('# GENERATED FILE - DO NOT EDIT. Content-bound projection of A16.1 and Appendix H.');$l.Add('schema_version = "eliot-conformance-v2"');$l.Add('authority_status = "GENERATED_PROJECTION"');$l.Add('provenance_mode = "CONTENT_BOUND"');$l.Add("architecture_source_path = $(Toml (Rel $ArchitecturePath))");$l.Add("implementation_source_path = $(Toml (Rel $ImplementationPath))");$l.Add("generator_path = $(Toml (Rel $GeneratorPath))");$l.Add("verifier_path = $(Toml (Rel $VerifierPath))");$l.Add("decision_path = $(Toml (Rel $DecisionPath))");$l.Add("architecture_source_sha256 = $(Toml $m.AH)");$l.Add("implementation_source_sha256 = $(Toml $m.IH)");$l.Add("normalized_pair_sha256 = $(Toml $m.PH)");$l.Add("generator_source_sha256 = $(Toml $m.GH)");$l.Add("verifier_source_sha256 = $(Toml $m.VH)");$l.Add("decision_source_sha256 = $(Toml $m.DH)");$l.Add('anchor_count = 58');$l.Add('');foreach($a in $m.A){$r=$m.By[$a.Id];$p=Scope $r.ScopeOwner;$l.Add('[[requirement]]');$l.Add("id = $(Toml $a.Id)");$l.Add("class = $(Toml $a.Class)");$l.Add("decision = $(Toml (Norm $a.Decision))");$l.Add("owner = $(Toml $p.Owner)");$l.Add("source_handles = $(TomlArray $p.Handles)");$l.Add('support = "UNKNOWN"');$l.Add('invalidation = []');$l.Add("observable_proof = $(Toml (Norm $r.Proof))");$l.Add('')};(($l -join "`n")+"`n")}
function Json($o){$o|ConvertTo-Json -Depth 30}
function Envelope($m,[string]$ch){$sources=@([ordered]@{path=(Rel $ArchitecturePath);role='current repository normative projection';sha256=$m.AH},[ordered]@{path=(Rel $ImplementationPath);role='current repository normative projection';sha256=$m.IH},[ordered]@{path=(Rel $DecisionPath);role='resolved result-envelope program revision';sha256=$m.DH});$s=[ordered]@{disposition='completed';artifacts=@([ordered]@{path='docs/conformance.toml';role='generated projection';sha256=$ch},[ordered]@{path='swarm/results/W1-04-implementation.json';role='supporting implementation evidence';sha256='supporting-file-not-authority'});evidence=@('58 A16.1 anchors are deterministically projected to 58 Appendix H rows with UNKNOWN support and empty invalidation by default.');discriminator_before=[ordered]@{name='anchor-bijection';value='A16.1/Appendix H mapping and generated envelope required independent verification';status='observed'};discriminator_after=[ordered]@{name='anchor-bijection';value='58x58 exact ID bijection and content-bound BootstrapWorkResult wrapper';status='verified'};uncertainty=@('No generated support or invalidation evidence exists; UNKNOWN and [] remain honest defaults.');unresolved_questions=@('Per-anchor owner/support/invalidation semantics remain unresolved and require a separately admitted work item.');proposed_effects=@('Future implementation may add independently verified support/invalidation evidence; no product or authority contract is changed here.');evidence_lineage=@($sources|%{[ordered]@{path=[string]$_.path;sha256=[string]$_.sha256;role=[string]$_.role}});schema_version='eliot-w1-04-implementation-v2';authority_status='EVIDENCE_ONLY';work_item_id='W1-04';provenance_mode='CONTENT_BOUND';source_documents=$sources;normalized_pair_sha256=$m.PH;generator_path=(Rel $GeneratorPath);generator_source_sha256=$m.GH;verifier_path=(Rel $VerifierPath);verifier_source_sha256=$m.VH;result=[ordered]@{disposition='EVIDENCE_ONLY';anchors=58;bijection='58x58 exact ID bijection';support_default='UNKNOWN';invalidation_default=@();ordering='Architecture A16.1 canonical order';authority='generated projection only; no manual mapping source'};contract_challenge_path='swarm/challenges/W1-RESULT-ENVELOPE-CONTRACT.md';verification=@('generator self-test and deterministic generation','generator check of conformance and implementation result','independent verifier self-test and normal verification');residuals=@('No generated evidence exists; every support value remains UNKNOWN and every invalidation list remains empty.','Result remains EVIDENCE_ONLY as BootstrapWorkResult evidence; no terminal attempt is claimed.');authority_ceiling='EVIDENCE_ONLY; no terminal completion, release WIP, activation, or wave authorization.'};[ordered]@{schema_version='eliot.bootstrap-work-result.v1';authority_status='EVIDENCE_ONLY';work_item_id='W1-04';structured_result=$s}
}
function Keys($o,[string]$name,[string[]]$expected){$got=if($o -is [Collections.IDictionary]){@($o.Keys|%{[string]$_})}else{@($o.PSObject.Properties.Name)};if((@($got|sort) -join '|') -cne (@($expected|sort) -join '|')){throw "$name has missing or extra fields: $($got -join ',')"}}
function CheckResult($actual,$m,[string]$ch){$expected=Envelope $m $ch; $names=if($actual -is [Collections.IDictionary]){@($actual.Keys|%{[string]$_})}else{@($actual.PSObject.Properties.Name)};foreach($requiredTop in @('authority_status','schema_version','structured_result','work_item_id')){if($requiredTop -notin $names){throw "BootstrapWorkResult missing field: $requiredTop"}};if(@($names).Count -ne 4){throw 'BootstrapWorkResult has extra fields'};if($actual.schema_version -cne 'eliot.bootstrap-work-result.v1' -or $actual.authority_status -cne 'EVIDENCE_ONLY' -or $actual.work_item_id -ne 'W1-04'){throw 'BootstrapWorkResult wrapper fields mismatch'};if($actual.PSObject.Properties.Name -contains 'terminal_update' -or $actual.PSObject.Properties.Name -contains 'attempt_id'){throw 'forbidden terminal fields present'};$snames=if($actual.structured_result -is [Collections.IDictionary]){@($actual.structured_result.Keys|%{[string]$_})}else{@($actual.structured_result.PSObject.Properties.Name)};foreach($required in @('artifacts','authority_ceiling','discriminator_after','discriminator_before','disposition','evidence','evidence_lineage','proposed_effects','uncertainty','unresolved_questions')){if($required -notin $snames){throw "structured_result missing required field: $required"}};if($actual.structured_result.disposition -notin @('completed','challenged','blocked','failed')){throw 'invalid structured_result disposition'};if((Json $actual).Contains('attempt_id') -or (Json $actual).Contains('terminal_update')){throw 'forbidden terminal field text present'};foreach($p in $expected.Keys){$av=Json $actual.$p;$ev=Json $expected[$p];if($av -cne $ev){throw "result envelope field tampered: $p"}}}
function SelfTest{$m=Model;$good=Conformance $m;$bad=$good.Replace('anchor_count = 58','anchor_count = 57');if($bad -eq$good){throw 'conformance tamper fixture failed'};$e=Envelope $m (TextSha $good);CheckResult $e $m (TextSha $good);$e.structured_result.result.authority='tampered';try{CheckResult $e $m (TextSha $good);throw 'result authority tamper accepted'}catch{if($_.Exception.Message -notmatch 'tampered|result envelope field'){throw}};Write-Output 'SELFTEST PASS: 58x58 model, content-bound determinism, TOML escaping, exact BootstrapWorkResult wrapper, and terminal-field rejection'}
if($SelfTest){SelfTest;exit 0};$m=Model;if(-not(Test-Path $ConformancePath)){throw "missing conformance artifact: $ConformancePath"};$expected=Conformance $m;$actual=Get-Content -LiteralPath $ConformancePath -Raw;if($actual -cne$expected){throw 'conformance.toml is stale, tampered, or non-deterministic'};if((Select-String -LiteralPath $ConformancePath -Pattern '(?m)^support = "UNKNOWN"$').Count -ne 58){throw 'support UNKNOWN count is not 58'};if((Select-String -LiteralPath $ConformancePath -Pattern '(?m)^invalidation = \[\]$').Count -ne 58){throw 'invalidation default count is not 58'};$ch=Sha $ConformancePath;foreach($rp in @($ResultPath,$SupportingResultPath)){if(-not(Test-Path $rp)){throw "missing result artifact: $rp"};$r=Get-Content -LiteralPath $rp -Raw|ConvertFrom-Json -Depth 30;CheckResult $r $m $ch};Write-Output 'VERIFY PASS: 58x58 bijection, content-bound hashes, exact TOML projection, UNKNOWN honesty, canonical W1-04 result, and supporting evidence wrapper'
